update areatrigger_tavern set name=' 西部荒野 - 哨兵岭' where id=71;
update areatrigger_tavern set name='艾尔文森林 - 闪金镇 - 狮王之傲旅店' where id=562;
update areatrigger_tavern set name='赤脊山 - 湖畔镇 - 湖畔镇旅店' where id=682;
update areatrigger_tavern set name='暮色森林 - 夜色镇 - 血鸦旅店' where id=707;
update areatrigger_tavern set name='希尔斯面莱德丘陵 - 南海镇' where id=708;
update areatrigger_tavern set name='尘泥沼泽 - 塞拉摩岛' where id=709;
update areatrigger_tavern set name='丹莫罗 - 卡拉诺斯 - 雷酒酿制厂' where id=710;
update areatrigger_tavern set name='洛克莫丹 - 塞尔萨玛 - 烈酒旅店' where id=712;
update areatrigger_tavern set name='湿地 - 米奈希尔港 - 深水旅店' where id=713;
update areatrigger_tavern set name='泰达希尔 - 多兰纳尔' where id=715;
update areatrigger_tavern set name='黑海岸 - 奥伯丁' where id=716;
update areatrigger_tavern set name='灰谷 - 阿斯特兰纳' where id=717;
update areatrigger_tavern set name='提瑞斯法林地 - 布瑞尔 - 恐惧之木旅店' where id=719;
update areatrigger_tavern set name='银松森林 - 瑟伯切尔' where id=720;
update areatrigger_tavern set name='希尔斯布莱德丘陵 - 塔伦米尔' where id=721;
update areatrigger_tavern set name='莫高雷 - 血蹄村' where id=722;
update areatrigger_tavern set name='贫瘠之地 - 十字路口' where id=742;
update areatrigger_tavern set name='贫瘠之地 - 棘齿城' where id=743;
update areatrigger_tavern set name='杜隆塔尔 - 剃刀岭' where id=843;
update areatrigger_tavern set name='悲伤沼泽 - 斯通纳德' where id=844;
update areatrigger_tavern set name='荆棘谷 - 藏宝海湾' where id=862;
update areatrigger_tavern set name='贫瘠之地 - 陶拉祖营地' where id=982;
update areatrigger_tavern set name='秘血岛 秘血岗哨酒馆' where id=4241;
update areatrigger_tavern set name='石爪山脉 - 烈日石居' where id=1022;
update areatrigger_tavern set name='塔纳利斯 - 加基森' where id=1023;
update areatrigger_tavern set name='菲拉斯 - 羽月要塞' where id=1024;
update areatrigger_tavern set name='菲拉斯 - 莫沙彻营地' where id=1025;
update areatrigger_tavern set name='荒芜之地 - 卡加斯' where id=1606;
update areatrigger_tavern set name='阿拉希高地 - 落锤镇' where id=1646;
update areatrigger_tavern set name='凄凉之地 - 尼耶尔前哨站' where id=2266;
update areatrigger_tavern set name='凄凉之地 - 葬影村' where id=2267;
update areatrigger_tavern set name='千针石林 - 乱风岗' where id=2286;
update areatrigger_tavern set name='冬泉谷 - 永望镇' where id=2287;
update areatrigger_tavern set name='灰谷 - 碎木岗哨' where id=2610;
update areatrigger_tavern set name='暴风城(入口)' where id=2786;
update areatrigger_tavern set name='幽魂之地 - 塔奎林旅店' where id=4108;
update areatrigger_tavern set name='碧蓝岗哨 Inn' where id=4240;
update areatrigger_tavern set name='萨尔玛旅店' where id=4336;
update areatrigger_tavern set name='荣耀堡旅店' where id=4337;
update areatrigger_tavern set name='萨布拉金旅店' where id=4373;
update areatrigger_tavern set name='加拉达 Inn' where id=4375;
update areatrigger_tavern set name='泰拉尔 Inn' where id=4376;
update areatrigger_tavern set name='奥蕾莉娅要塞 Inn' where id=4377;
update areatrigger_tavern set name='赛纳里奥避难所' where id=4382;
update areatrigger_tavern set name='猎鹰之翼广场 Inn' where id=4486;
update areatrigger_tavern set name='影月村 Inn' where id=4526;
update areatrigger_tavern set name='蛮鎚要塞 Inn' where id=4528;
update areatrigger_tavern set name='莫克纳萨村 Inn' where id=4595;
update areatrigger_tavern set name='星光圣所 Inn' where id=4607;
update areatrigger_tavern set name='精灵城 - 泰雷多尔 Inn' where id=4374;
update areatrigger_tavern set name='奥雷柏尔营地 Inn' where id=4383;
update areatrigger_tavern set name='塔哈玛特神殿 Inn' where id=4381;
update areatrigger_tavern set name='希尔瓦纳 Inn' where id=4499;
update areatrigger_tavern set name='托什雷的基地 Inn' where id=4558;
update areatrigger_tavern set name='雷神要塞 Inn' where id=4494;
update areatrigger_tavern set name='常青林 Inn' where id=4640;
update areatrigger_tavern set name='52区 Inn' where id=4521;
update areatrigger_tavern set name='风暴尖塔 Inn' where id=4555;
update areatrigger_tavern set name='沙塔尔祭坛 Inn' where id=4577;
update areatrigger_tavern set name='奥特兰克山脉 - 斯坦恩布莱德' where id=178;
update areatrigger_tavern set name='辛特兰 - 蛮锤城堡' where id=1042;
update areatrigger_tavern set name='恶齿村' where id=3690;
update areatrigger_tavern set name='格罗姆高营地' where id=3886;
update areatrigger_tavern set name='圣光之愿礼拜堂' where id=4058;
update areatrigger_tavern set name='塞纳里奥要塞' where id=3985;
update areatrigger_tavern set name='石爪峰' where id=4090;
update areatrigger_tavern set name='幽暗城' where id=3547;
update areatrigger_tavern set name='铁炉堡' where id=4769;
update areatrigger_tavern set name='泥链镇 Inn' where id=4714;
update areatrigger_tavern set name='蕨墙村 Inn' where id=4775;
update areatrigger_tavern set name='奎尔丹纳斯岛, 太阳之井高地 Inn' where id=4847;
update areatrigger_tavern set name='无畏要塞 Inn' where id=4961;
update areatrigger_tavern set name='菲兹兰克机场 Inn' where id=4867;
update areatrigger_tavern set name='乌努比 Inn' where id=4977;
update areatrigger_tavern set name='牦牛村 Inn' where id=4868;
update areatrigger_tavern set name='战歌要塞' where id=4910;
update areatrigger_tavern set name='博古洛克前哨站 Inn' where id=4861;
update areatrigger_tavern set name='冬蹄营地 Inn' where id=4755;
update areatrigger_tavern set name='维德瓦堡垒 Inn' where id=4756;
update areatrigger_tavern set name='阿格玛之锤' where id=5045;
update areatrigger_tavern set name='群星之墓' where id=4964;
update areatrigger_tavern set name='琥珀松木营地 Inn' where id=4965;
update areatrigger_tavern set name='月溪旅营地' where id=4966;
update areatrigger_tavern set name='欧尼瓦营地' where id=4967;
update areatrigger_tavern set name='征服堡' where id=4970;
update areatrigger_tavern set name='莫亚基港口' where id=4975;
update areatrigger_tavern set name='卡玛古' where id=4976;
update areatrigger_tavern set name='怨毒镇' where id=4979;
update areatrigger_tavern set name='暮冬要塞' where id=4993;
update areatrigger_tavern set name='锐矛营地' where id=5030;
update areatrigger_tavern set name='银色前沿' where id=5062;
update areatrigger_tavern set name='希姆托加' where id=5164;
update areatrigger_tavern set name='冰霜堡' where id=5182;
update areatrigger_tavern set name='K3' where id=5183;
update areatrigger_tavern set name='布伦希尔达村' where id=5200;
update areatrigger_tavern set name='布德克拉格庇护所' where id=5204;
update areatrigger_tavern set name='奈辛瓦里营地' where id=5217;
update areatrigger_tavern set name='银白先锋驻地' where id=5227;
update areatrigger_tavern set name='唐卡洛营地' where id=5323;
update areatrigger_tavern set name='克拉苏斯平台' where id=5327;
update areatrigger_tavern set name='西部卫戍要塞 Inn' where id=4753;
update areatrigger_tavern set name='晴风村 Inn' where id=4265;
update areatrigger_tavern set name='荆棘谷 - 奈辛瓦里远征队营地' where id=98;
update areatrigger_tavern set name='塔奎林 - Upper level Inn' where id=4109;
update areatrigger_tavern set name='塞纳里奥避难所 - Outside Inn' where id=4300;
update areatrigger_tavern set name='裂石堡 Inn' where id=4378;
update areatrigger_tavern set name='猎鹰岗哨 Inn' where id=4380;
update areatrigger_tavern set name='旧希尔斯布莱德丘陵 Inn' where id=4498;
update areatrigger_tavern set name='群星圣殿 - Upper level Inn' where id=4608;
update areatrigger_tavern set name='龙眠神殿1' where id=5314;
update areatrigger_tavern set name='龙眠神殿2' where id=5315;
update areatrigger_tavern set name='龙眠神殿3' where id=5316;
update areatrigger_tavern set name='龙眠神殿4' where id=5317;
