update trinity_string set content_default='您應該選擇角色或生物。' where entry=1;
update trinity_string set content_default='您應該選擇一個生物。' where entry=2;
update trinity_string set content_default='|cffff 0000[ 系統消息]: %s| r' where entry=3;
update trinity_string set content_default='|cffff 0000[ 活動消息]: %s| r' where entry=4;
update trinity_string set content_default='這裡沒有此命令的幫助信息' where entry=5;
update trinity_string set content_default='這個命令不存在' where entry=6;
update trinity_string set content_default='這裡沒有此類子命令' where entry=7;
update trinity_string set content_default='命令%s有子命令:' where entry=8;
update trinity_string set content_default='你可以使用的命令有:' where entry=9;
update trinity_string set content_default='命令語法格式錯誤。' where entry=10;
update trinity_string set content_default='你的賬號級別是: %i' where entry=11;
update trinity_string set content_default='在線人數: %u(最多時: %u) 排隊人數: %u(最多時: %u)' where entry=12;
update trinity_string set content_default='服務器正常運行時間: %s' where entry=13;
update trinity_string set content_default='系統提示：玩家數據保存成功。' where entry=14;
update trinity_string set content_default='系統提示：保存所有玩家數據成功。' where entry=15;
update trinity_string set content_default='系統提示：在此服務器上有以下在線的ＧＭ:' where entry=16;
update trinity_string set content_default='系統提示：當前沒有 G M 登錄在這台服務器上。' where entry=17;
update trinity_string set content_default='系統提示：當處於飛行中時，無法這樣做。' where entry=18;
update trinity_string set content_default='系統提示：目標在飛行中，你無法這樣做。' where entry=20;
update trinity_string set content_default='系統提示：在戰場裡無法這樣做。' where entry=19;
update trinity_string set content_default='%s 正在飛行中，命令無效。' where entry=21;
update trinity_string set content_default='系統提示：你沒有在騎乘狀態，因此你不能卸下騎乘。' where entry=22;
update trinity_string set content_default='系統提示：在戰鬥中無法這樣做。' where entry=23;
update trinity_string set content_default='系統提示：您最近已經使用過它。' where entry=24;
update trinity_string set content_default='系統提示：您的密碼不能設置超過 16 個字符長度 (客戶極限), 密碼沒被改變' where entry=25;
update trinity_string set content_default='系統提示：密碼已經修改。' where entry=26;
update trinity_string set content_default='密碼錯誤' where entry=27;
update trinity_string set content_default='系統提示：你的賬號現在被鎖定。' where entry=28;
update trinity_string set content_default='系統提示：你的賬號已取消鎖定。' where entry=29;
update trinity_string set content_default=', 等級' where entry=30;
update trinity_string set content_default=' [已知的]' where entry=31;
update trinity_string set content_default=' [ 學習]' where entry=32;
update trinity_string set content_default=' [ 被動的]' where entry=33;
update trinity_string set content_default=' [ 天賦]' where entry=34;
update trinity_string set content_default=' [活躍的]' where entry=35;
update trinity_string set content_default=' [ 完成]' where entry=36;
update trinity_string set content_default=' (離線)' where entry=37;
update trinity_string set content_default='開' where entry=38;
update trinity_string set content_default='關' where entry=39;
update trinity_string set content_default='你是: %s' where entry=40;
update trinity_string set content_default='看得見的' where entry=41;
update trinity_string set content_default='看不見的' where entry=42;
update trinity_string set content_default='完成了' where entry=43;
update trinity_string set content_default='你' where entry=44;
update trinity_string set content_default=' <未知者>' where entry=45;
update trinity_string set content_default='<錯誤>' where entry=46;
update trinity_string set content_default='<非現有的角色>' where entry=47;
update trinity_string set content_default='未知者' where entry=48;
update trinity_string set content_default='你必須達到 %u 級後進入。' where entry=49;
update trinity_string set content_default='你必須達到 %u 級,並且擁有道具 %s 方可進入。' where entry=50;
update trinity_string set content_default='你好! 準備學習什麼技能嗎?' where entry=51;
update trinity_string set content_default='為項目的 Invaid 項目計數 (%u)%u' where entry=52;
update trinity_string set content_default='郵件不能有更多 %u 項目堆疊' where entry=53;
update trinity_string set content_default='新的密碼不匹配' where entry=54;
update trinity_string set content_default='你的密碼不能是長於16字節，密碼沒有變更!' where entry=55;
update trinity_string set content_default='"""那天的現在的信息: 

%s"""' where entry=56;
update trinity_string set content_default='使用世界分貝: %s' where entry=57;
update trinity_string set content_default='使用手寫體: %s' where entry=58;
update trinity_string set content_default='使用人 EventAI: %s' where entry=59;
update trinity_string set content_default='Online players: %u (max: %u)' where entry=60;
update trinity_string set content_default='使用者名稱: ' where entry=61;
update trinity_string set content_default='"""世界通報:

"""' where entry=100;
update trinity_string set content_default='""""""" 地圖: %u(%s) 地域: %u(%s) 地區: %u(%s)

X: %f Y: %f Z: %f"""""""' where entry=101;
update trinity_string set content_default='%s 已被遠距傳送。' where entry=102;
update trinity_string set content_default='你可以召喚一個玩家到你的副本，前提是必須在同一隊伍，而且你是隊長。' where entry=103;
update trinity_string set content_default='你無法傳送到玩家 %s 的副本，因為你們不在同一隊伍。' where entry=104;
update trinity_string set content_default='傳送到不是同一隊伍的玩家 %s 的副本需要開啟ＧＭ模式。' where entry=105;
update trinity_string set content_default='你無法傳送到玩家 %s 從副本到副本。' where entry=106;
update trinity_string set content_default='你不能召喚這個玩家 %s 從副本到副本。' where entry=107;
update trinity_string set content_default='你正在召喚 %s% s。' where entry=108;
update trinity_string set content_default='系統提示：你正在被 %s 召喚中。' where entry=109;
update trinity_string set content_default='你正在傳送 %s% s 到 %s。' where entry=110;
update trinity_string set content_default='系統提示：你正在被 %s 傳送。' where entry=111;
update trinity_string set content_default='玩家 (%s) 不存在。' where entry=112;
update trinity_string set content_default='出現在 %s 的地點。' where entry=113;
update trinity_string set content_default='%s 出現在你的位置。' where entry=114;
update trinity_string set content_default='無效參數。' where entry=115;
update trinity_string set content_default='沒有選定角色。' where entry=116;
update trinity_string set content_default='%s 不在同一小組裡。' where entry=117;
update trinity_string set content_default='你改變了 %s 的血量值 HP 到 %i/%i。' where entry=118;
update trinity_string set content_default='%s 改變了你的血量值 HP 到 % i/%i。' where entry=119;
update trinity_string set content_default='你改變了 %s 的魔法值超自然力量到 % i/%i。' where entry=120;
update trinity_string set content_default='%s 改變了你的魔法值超自然力量到 % i/%i。' where entry=121;
update trinity_string set content_default='你改變了 %s 的能量值能源到 % i/%i。' where entry=122;
update trinity_string set content_default='%s 改變了你的能量值能源到 % i/%i。' where entry=123;
update trinity_string set content_default='當前的能量: %u' where entry=124;
update trinity_string set content_default='你改變了 %s 的怒氣值憤怒到 %i/%i。' where entry=125;
update trinity_string set content_default='%s 改變了你的怒氣值憤怒到 %i/%i。' where entry=126;
update trinity_string set content_default='你改變了 %s 的等級 LVL 到 % i。' where entry=127;
update trinity_string set content_default='GUID%i, 陣營是 %i, 旗子是 %i, npcflag 是 %i, DY 旗子是 %i' where entry=128;
update trinity_string set content_default='錯誤陣式: %u.(在 factiontemplate.dbc 中不發現)' where entry=129;
update trinity_string set content_default='你改變了 GUID=%i"s 陣營到 %i, 旗子到 %i,' where entry=130;
update trinity_string set content_default='你改變了 spellflatid=%i, val=%i, 標誌 =%i' where entry=131;
update trinity_string set content_default='%s 改變了你的 spellflatid=%i, val=%i, 標誌 =%i。' where entry=132;
update trinity_string set content_default='%s 獲得了所有的計程節點 (直到註銷).' where entry=133;
update trinity_string set content_default='%s 沒有更多地可獲得的計程節點 (僅顯示容易接近的).' where entry=134;
update trinity_string set content_default='%s 給你進入所有計程車節點 (直到註銷).' where entry=135;
update trinity_string set content_default='%s 已取消進出所有計程車節點 (僅顯示仍然容易接近的).' where entry=136;
update trinity_string set content_default='你設置了所有的速度到 %2.2 f 從數值 %s。' where entry=137;
update trinity_string set content_default='%s 設置了你所有的速度到 %2.2 f 從數值。' where entry=138;
update trinity_string set content_default='你設置了移動速度到 %2.2 f 從數值 %s。' where entry=139;
update trinity_string set content_default='%s 設置了你的移動速度到 %2.2 f 從數值。' where entry=140;
update trinity_string set content_default='你設置了游泳速度到 %2.2 f 從數值 %s。' where entry=141;
update trinity_string set content_default='%s 設置了你的游泳速度到 %2.2 f 從數值。' where entry=142;
update trinity_string set content_default='設置了後退速度到 %2.2 f 從數值 %s。' where entry=143;
update trinity_string set content_default='%s 設置了你的後退速度到 %2.2 f 從數值。' where entry=144;
update trinity_string set content_default='你設置了飛行速度到 %2.2 f 從數值 %s。' where entry=145;
update trinity_string set content_default='%s 設置你的飛行速度到 %2.2 f 從數值。' where entry=146;
update trinity_string set content_default='你設置了這個比例 %2.2 f%s。' where entry=147;
update trinity_string set content_default='%s 設置你的比例為 %2.2 f。' where entry=148;
update trinity_string set content_default='沒有此類騎術。' where entry=149;
update trinity_string set content_default='你把一個騎術送給 %s。' where entry=150;
update trinity_string set content_default='%s 送給你一個騎術。' where entry=151;
update trinity_string set content_default='"""USER1: %i,增加: %i, DIF: %i

"""' where entry=152;
update trinity_string set content_default='你拿走了所有的銅幣從 %s。' where entry=153;
update trinity_string set content_default='%s 拿走了你所有的銅幣。' where entry=154;
update trinity_string set content_default='你拿走了 %i 銅幣從 % s。' where entry=155;
update trinity_string set content_default='%s 拿走了 % i 銅幣從你這裡。' where entry=156;
update trinity_string set content_default='你把 %i 銅幣給了 % s。' where entry=157;
update trinity_string set content_default='%s 給你 % i 銅幣。' where entry=158;
update trinity_string set content_default='你聽到聲音 %u。' where entry=159;
update trinity_string set content_default='"""用戶2: %i,增加: %i, 結果: %i

"""' where entry=160;
update trinity_string set content_default='離開的一點點 %在領域中的 i%i。' where entry=161;
update trinity_string set content_default='固定的一點點 %在領域中的 i%i。' where entry=162;
update trinity_string set content_default='遠距傳送地點表是空的!' where entry=163;
update trinity_string set content_default='遠距傳送地點沒被發現!' where entry=164;
update trinity_string set content_default='需要搜索參數。' where entry=165;
update trinity_string set content_default='沒有遠距傳物地點匹配您的請求。' where entry=166;
update trinity_string set content_default='發現地點是: ' where entry=168;
update trinity_string set content_default='郵件寄給 %s' where entry=169;
update trinity_string set content_default='你試著聽聲音 %u 但是它並不存在。' where entry=170;
update trinity_string set content_default='你不能傳送自己到自己!' where entry=171;
update trinity_string set content_default='伺候器控制台指令' where entry=172;
update trinity_string set content_default='你改變了古代北歐文字的力量 %s 到 %i/%i。' where entry=173;
update trinity_string set content_default='%s 改變了你的古代北歐文字力量到 %i/%i。' where entry=174;
update trinity_string set content_default='Liquid level: %f, ground: %f, type: %u, flags %u, status: %d.' where entry=175;
update trinity_string set content_default='沒有選擇。' where entry=200;
update trinity_string set content_default='Object GUID is: lowpart %u highpart %X' where entry=201;
update trinity_string set content_default='這個名字長度超過了 %i 字符。' where entry=202;
update trinity_string set content_default='錯誤，名字只能包含字符 A-Z 和 a-z。' where entry=203;
update trinity_string set content_default='次級名字太長超過了 %i 字符。' where entry=204;
update trinity_string set content_default='未能實施。' where entry=205;
update trinity_string set content_default='物品 "% i""% s" 以加入到列表且最大數 "% i" 復生時間 "% i"' where entry=206;
update trinity_string set content_default='物品 "% i" 在數據庫裡沒有找到。' where entry=207;
update trinity_string set content_default='物品 "% i""% s" 已經從商人列表中刪除。' where entry=208;
update trinity_string set content_default='物品 "% i" 沒有找到在商人的列表裡。' where entry=209;
update trinity_string set content_default='法術 %s 重置。' where entry=211;
update trinity_string set content_default='法術 %s 將在下次登陸時重置。' where entry=212;
update trinity_string set content_default='天賦 %s 重置。' where entry=213;
update trinity_string set content_default='天賦 %s 將在下次登陸時重置。' where entry=214;
update trinity_string set content_default='你的法術已經重置了。' where entry=215;
update trinity_string set content_default='你的天賦已經重置了。' where entry=216;
update trinity_string set content_default='未知的參數 "% s" 為。resetall 命令。 鍵入完整的正確參數名字。' where entry=217;
update trinity_string set content_default='法術將重置在所有玩家在重新登錄後。 強烈推薦重新登錄!' where entry=218;
update trinity_string set content_default='天賦將重置在所有玩家在重新登錄後。 強烈推薦重新登錄!' where entry=219;
update trinity_string set content_default='生物 (GUID: %u) 沒有飛行點發現。' where entry=220;
update trinity_string set content_default='生物 (GUID: %u) 飛行終點沒有找到。' where entry=221;
update trinity_string set content_default='生物 (GUID: %u) 沒有飛行點發現 - 請用 " wpguid". 現在設法發現它由它的位置。。。' where entry=222;
update trinity_string set content_default='生物 (GUID: %u) 沒有飛行點發現 - 這是一個芒果分貝問題.(獨身者漂流物)' where entry=223;
update trinity_string set content_default='選擇的生物被忽略 - 提供的 GUID 已經被佔用。' where entry=224;
update trinity_string set content_default='生物 (GUID: %u) 沒有找到。' where entry=225;
update trinity_string set content_default='您必須選擇一個視覺飛行點。' where entry=226;
update trinity_string set content_default='沒有找到視覺飛行點。' where entry=227;
update trinity_string set content_default='不能創建視覺飛行點的生物ID: %d' where entry=228;
update trinity_string set content_default='所有視覺飛行點消除。' where entry=229;
update trinity_string set content_default='不能創建飛行點- 生物的ID: %d' where entry=230;
update trinity_string set content_default='沒有 GUID 被提供。' where entry=231;
update trinity_string set content_default='沒有提供飛行點數值。' where entry=232;
update trinity_string set content_default='根據要求為 "% s".' where entry=233;
update trinity_string set content_default='飛行點 %i 添加到 GUID: %d' where entry=234;
update trinity_string set content_default='飛行點 %d 已添加。' where entry=235;
update trinity_string set content_default='飛行點已變動。' where entry=236;
update trinity_string set content_default='飛行點 %s 已修改。' where entry=237;
update trinity_string set content_default='飛行點出口成功。' where entry=238;
update trinity_string set content_default='沒有飛行點被發現在數據庫裡。' where entry=239;
update trinity_string set content_default='文件已導入。' where entry=240;
update trinity_string set content_default='飛行點取消。' where entry=241;
update trinity_string set content_default='警告: 不能刪除這個飛行點從世界裡且ID: %d' where entry=242;
update trinity_string set content_default='出現這種情況，是因為飛行點過於遠離你。' where entry=243;
update trinity_string set content_default='這個飛行點已經從數據庫刪除，但不是從世界這裡。' where entry=244;
update trinity_string set content_default='他們將消失，當服務器重新啟動之後。' where entry=245;
update trinity_string set content_default='飛行點 %d: 生物信息: %s, GUID: %d' where entry=246;
update trinity_string set content_default='等待時間: %d' where entry=247;
update trinity_string set content_default='模型 %d: %d' where entry=248;
update trinity_string set content_default='表情: %d' where entry=249;
update trinity_string set content_default='技能: %d' where entry=250;
update trinity_string set content_default='本文%d(ID: %i): %s' where entry=251;
update trinity_string set content_default='AI脚本: %s' where entry=252;
update trinity_string set content_default='強制修改玩家名 %s ，將於下次登錄時生效。' where entry=253;
update trinity_string set content_default='強制修改玩家名 %s(GUID#%u) ，將於下次登錄時生效。' where entry=254;
update trinity_string set content_default='飛行點-生物 (GUID: %u) 沒有找到。' where entry=255;
update trinity_string set content_default='不能查找 NPC。。。' where entry=256;
update trinity_string set content_default='生物運動方式設置為 "% s", 飛行點去除 (如果任何).' where entry=257;
update trinity_string set content_default='生物運動方式設置為 "% s", 飛行點沒有去除。' where entry=258;
update trinity_string set content_default='錯誤值, 在或上的請用走開' where entry=259;
update trinity_string set content_default='設置已保存。' where entry=260;
update trinity_string set content_default='設置已保存，你可能需要重新清理你的客戶緩存。' where entry=261;
update trinity_string set content_default='區域觸發 (傳送門) ID %u 沒有發現! ' where entry=262;
update trinity_string set content_default='目標地圖或坐標無效 (X: %f Y: %f MapId: %u)' where entry=263;
update trinity_string set content_default='區域傳送門無效 (X: %f Y: %f AreaId: %u)' where entry=264;
update trinity_string set content_default='地域 %u(%s) 是地圖 %u(%s)的部份' where entry=265;
update trinity_string set content_default='沒任何發現!' where entry=266;
update trinity_string set content_default='對像沒有找到!' where entry=267;
update trinity_string set content_default='生物沒有找到!' where entry=268;
update trinity_string set content_default='警告: 怪物发现超过一次 - 你将使用的是第一个在DB数据里的记录.' where entry=269;
update trinity_string set content_default='生物已經移除。' where entry=270;
update trinity_string set content_default='生物已經移動。 ' where entry=271;
update trinity_string set content_default='生物 (GUID:%u) 必須與玩家在同樣的地圖!' where entry=272;
update trinity_string set content_default='遊戲對像 (GUID: %u) 沒有找到。' where entry=273;
update trinity_string set content_default='遊戲對像 (GUID: %u) 有一個參考於沒有找到生物 %u 是名單，不能被刪除。' where entry=274;
update trinity_string set content_default='遊戲對像 (GUID: %u) 去除。' where entry=275;
update trinity_string set content_default='遊戲對像 (GUID: %u) 轉動。' where entry=276;
update trinity_string set content_default='遊戲對像 (GUID: %u) 移動。' where entry=277;
update trinity_string set content_default='你必須選擇一個商人' where entry=278;
update trinity_string set content_default='你必須使用物品的遺傳素質' where entry=279;
update trinity_string set content_default='商人設置了太多的物品 (最多 128)' where entry=280;
update trinity_string set content_default='你不能踢出你自己，使用退出代替。' where entry=281;
update trinity_string set content_default='角色 %s 已踢出。' where entry=282;
update trinity_string set content_default='接受悄悄話: %s' where entry=284;
update trinity_string set content_default='接受悄悄話: 在' where entry=285;
update trinity_string set content_default='接受悄悄話: 走開' where entry=286;
update trinity_string set content_default='生物 (GUID: %u) 沒有找到。' where entry=287;
update trinity_string set content_default='票數量: %i 出示新的票: %s' where entry=288;
update trinity_string set content_default='新票開始於 %s' where entry=289;
update trinity_string set content_default='"""票 %s(最後的更新: %s):

%s"""' where entry=290;
update trinity_string set content_default='新票顯示: 在' where entry=291;
update trinity_string set content_default='新票顯示: 走開' where entry=292;
update trinity_string set content_default='票 %i 不存在。' where entry=293;
update trinity_string set content_default='所有票已刪除。' where entry=294;
update trinity_string set content_default='角色 %s 票已刪除。' where entry=295;
update trinity_string set content_default='票已刪除。' where entry=296;
update trinity_string set content_default='復生間隔改變為: %i' where entry=297;
update trinity_string set content_default='復生時間改變為: %i' where entry=298;
update trinity_string set content_default=' %s 的榮譽被設置到 % u!' where entry=299;
update trinity_string set content_default='你被關閉了 %s 的聊天時間 % u 分鐘。' where entry=301;
update trinity_string set content_default='玩的聊天已經可以使用。' where entry=302;
update trinity_string set content_default='你的聊天已經可以使用。' where entry=303;
update trinity_string set content_default='你已經可以使用 %s 的聊天了。' where entry=304;
update trinity_string set content_default='陣營 %s(%u) 名譽 %s 被設定成 %5 d!' where entry=305;
update trinity_string set content_default='競技場點 %s 被設定成 %u!' where entry=306;
update trinity_string set content_default='沒有陣營被發現' where entry=307;
update trinity_string set content_default='陣營 %i 未知!' where entry=308;
update trinity_string set content_default='無效的參數 %s' where entry=309;
update trinity_string set content_default='三角州必須是在 0之間和 %d(包含)在內的' where entry=310;
update trinity_string set content_default='%d - |cffffffff|Hfaction:%d|h[%s]|h|r' where entry=311;
update trinity_string set content_default=' [看得見的]' where entry=312;
update trinity_string set content_default=' [在戰爭]' where entry=313;
update trinity_string set content_default=' [和平被迫的]' where entry=314;
update trinity_string set content_default=' [隱藏的]' where entry=315;
update trinity_string set content_default=' [看不見的被迫]' where entry=316;
update trinity_string set content_default=' [不活動的]' where entry=317;
update trinity_string set content_default='仇恨' where entry=318;
update trinity_string set content_default='敵對' where entry=319;
update trinity_string set content_default='不友好' where entry=320;
update trinity_string set content_default='中立' where entry=321;
update trinity_string set content_default='友好的' where entry=322;
update trinity_string set content_default='榮譽的' where entry=323;
update trinity_string set content_default='尊敬的' where entry=324;
update trinity_string set content_default='高貴的' where entry=325;
update trinity_string set content_default='陣營 %s(%u) 不能有榮譽。' where entry=326;
update trinity_string set content_default=' [沒有名譽]' where entry=327;
update trinity_string set content_default='在帳戶的角色 %s(ID: %u)' where entry=328;
update trinity_string set content_default='  %s (GUID %u)' where entry=329;
update trinity_string set content_default='沒有玩家發現!' where entry=330;
update trinity_string set content_default='廣大的項目費用 %u 不存在' where entry=331;
update trinity_string set content_default='開啟GM狀態' where entry=332;
update trinity_string set content_default='關閉GM狀態' where entry=333;
update trinity_string set content_default='GM 閒談半自動防空警戒管制組織是在' where entry=334;
update trinity_string set content_default='GM 閒談半自動防空警戒管制組織是走開' where entry=335;
update trinity_string set content_default='你修理所有的 %s 項目。' where entry=336;
update trinity_string set content_default='你所有的項目修復的被 %s。' where entry=337;
update trinity_string set content_default='你組 waterwalk 模態 %s 為 %s。' where entry=338;
update trinity_string set content_default='你的 waterwalk 模態 %s 被 %s。' where entry=339;
update trinity_string set content_default='%s 現在是下列各項你。' where entry=340;
update trinity_string set content_default='%s 是不下列各項你。' where entry=341;
update trinity_string set content_default='%s 是現在不下列各項你。' where entry=342;
update trinity_string set content_default='人 (進入: %u) 不能夠是馴養。' where entry=343;
update trinity_string set content_default='你已經有伴侶動物。' where entry=344;
update trinity_string set content_default='被迫的為玩家定制 %s 將會是在下一個登錄請求了。' where entry=345;
update trinity_string set content_default='被迫的為玩家定制 %s(GUID#%u) 意志是在下一個登錄請求了。' where entry=346;
update trinity_string set content_default='TaxiNode ID %u 不發現!' where entry=347;
update trinity_string set content_default='遊戲物體 (進入: %u) 有病人數據而且不能是產' where entry=348;
update trinity_string set content_default='|cffff 0000[ 系統信息]:|rScripts 再裝貨' where entry=400;
update trinity_string set content_default='你改變了 %s 的安全等級為 % i。' where entry=401;
update trinity_string set content_default='%s 改變了你的安全等級為 % i。' where entry=402;
update trinity_string set content_default='你這是低的防護等級。' where entry=403;
update trinity_string set content_default='生物移動點取消。' where entry=404;
update trinity_string set content_default='生物移動點生效。' where entry=405;
update trinity_string set content_default='這個區域的天氣不能被更改。' where entry=406;
update trinity_string set content_default='本服務器天氣系統取消。' where entry=407;
update trinity_string set content_default='%s 被禁止的為 % s。 操作: %s。' where entry=408;
update trinity_string set content_default='%s 被永久禁止的為 % s。' where entry=409;
update trinity_string set content_default='%s% s 不發現' where entry=410;
update trinity_string set content_default='%s 已解除禁止。' where entry=411;
update trinity_string set content_default='出現錯誤取消禁令 %s。' where entry=412;
update trinity_string set content_default='沒有這個帳戶。' where entry=413;
update trinity_string set content_default='沒有這個角色。' where entry=414;
update trinity_string set content_default='沒有這樣的 IP 在禁止名單。' where entry=415;
update trinity_string set content_default='賬號 %s 從來沒被禁止。' where entry=416;
update trinity_string set content_default='歷史禁止帳戶 %s:' where entry=417;
update trinity_string set content_default='禁止日期: %s 禁止時間: %s 激活間隔: %s 原因: %s 操作者: %s' where entry=418;
update trinity_string set content_default='信息。' where entry=419;
update trinity_string set content_default='從不' where entry=420;
update trinity_string set content_default='是的' where entry=421;
update trinity_string set content_default='沒有' where entry=422;
update trinity_string set content_default='IP 地址: %s 禁止日期: %s 解除禁止日期: %s 剩餘: %s R' where entry=423;
update trinity_string set content_default='沒有匹配的 IP 禁止地址。' where entry=424;
update trinity_string set content_default='沒有匹配的帳戶。' where entry=425;
update trinity_string set content_default='沒有禁用的賬號相匹配。' where entry=426;
update trinity_string set content_default='下面的 IP 地址符合您的格局:' where entry=427;
update trinity_string set content_default='以下帳戶匹配您的查詢:' where entry=428;
update trinity_string set content_default='你學會了許多法術或技能。' where entry=429;
update trinity_string set content_default='你已經學會了所有的會職業法術。' where entry=430;
update trinity_string set content_default='你已經學會了所有的本職業天賦。' where entry=431;
update trinity_string set content_default='你已經學會了所有的語言。' where entry=432;
update trinity_string set content_default='你學會了所有手工藝技能和食譜。' where entry=433;
update trinity_string set content_default='不能查找 "% s"' where entry=434;
update trinity_string set content_default='無效的物品遺傳素質: %u' where entry=435;
update trinity_string set content_default='沒有找到物品!' where entry=436;
update trinity_string set content_default='無效的遊戲物品對像遺傳素質: %u' where entry=437;
update trinity_string set content_default='找到物品 %u: %u( 庫存 %u 郵件 % u 拍賣 %u)' where entry=438;
update trinity_string set content_default='找到物品對像 %u: %u' where entry=439;
update trinity_string set content_default='無效的生物遺傳素質: %u' where entry=440;
update trinity_string set content_default='找到生物 %u: %u' where entry=441;
update trinity_string set content_default='沒有地區被發現!' where entry=442;
update trinity_string set content_default='沒有找到物品集!' where entry=443;
update trinity_string set content_default='沒有找到此技能!' where entry=444;
update trinity_string set content_default='沒有找到此法術!' where entry=445;
update trinity_string set content_default='沒有找到此任務!' where entry=446;
update trinity_string set content_default='沒有找到此生物!' where entry=447;
update trinity_string set content_default='沒有找到此遊戲物品對像!' where entry=448;
update trinity_string set content_default='墓地 #%u 不存在。' where entry=449;
update trinity_string set content_default='墓地 #%u 已經連接到區域 #% u(當前).' where entry=450;
update trinity_string set content_default='墓地 #%u 連接到區域 #% u(當前).' where entry=451;
update trinity_string set content_default='墓地 #%u 不能連接到子區域或不存在的區域 #% u(內部錯誤).' where entry=452;
update trinity_string set content_default='沒有陣營在墓地且遺傳素質=#%u, 請修復你的分貝數據庫' where entry=454;
update trinity_string set content_default='錯誤的隊伍, 請修復你的數據庫' where entry=455;
update trinity_string set content_default='任何' where entry=456;
update trinity_string set content_default='聯盟' where entry=457;
update trinity_string set content_default='部落' where entry=458;
update trinity_string set content_default='墓地ID #%u(陣營: %s) 是最近的距此區域 zoneID#%u。' where entry=459;
update trinity_string set content_default='區域地域 #%u 沒有一個連接的墓地。' where entry=460;
update trinity_string set content_default='區域地域 #%u 沒有一個連接的墓地為陣營陣營: %s。' where entry=461;
update trinity_string set content_default='遠距傳物地點已經存在!' where entry=462;
update trinity_string set content_default='遠距傳送地點增加。' where entry=463;
update trinity_string set content_default='遠距傳送地點沒增加: 數據庫錯誤。' where entry=464;
update trinity_string set content_default='遠距傳送地點被刪除。' where entry=465;
update trinity_string set content_default='沒有 taxinodes 發現!' where entry=466;
update trinity_string set content_default='目標單位 (單位) 有 %d 光環氣味:' where entry=467;
update trinity_string set content_default='遺傳素質: %d eff: %d 類型: %d 期間: %d maxduration: %d 名字: %s% s%s 投手: %s% u' where entry=468;
update trinity_string set content_default='目標單位有 %類型的 d 氣味 %d:' where entry=469;
update trinity_string set content_default='id: %d eff: %d amount: %d' where entry=470;
update trinity_string set content_default='任務 %u 沒有找到。' where entry=471;
update trinity_string set content_default='任務 %u 由物品觸發。 為正確工作，請, 添加物品到庫裡並且開始這個任務的正常方式: 。additem%u' where entry=472;
update trinity_string set content_default='任務清除。' where entry=473;
update trinity_string set content_default=' [ 獎賞]' where entry=474;
update trinity_string set content_default=' [ 完成]' where entry=475;
update trinity_string set content_default=' [活躍的]' where entry=476;
update trinity_string set content_default='%s 的飛行模式為 % s' where entry=477;
update trinity_string set content_default='操作代碼操作碼 %u 發送到 (送了到)%s' where entry=478;
update trinity_string set content_default='角色加載成功!' where entry=479;
update trinity_string set content_default='加載角色失敗!' where entry=480;
update trinity_string set content_default='卸載角色成功!' where entry=481;
update trinity_string set content_default='卸載角色失敗!' where entry=482;
update trinity_string set content_default='魔法 %u 破裂，並且不允許使用或學習!' where entry=483;
update trinity_string set content_default='技能值 %u(%s) 為角色 %s 設置到 % u 並且當前最大設置到 %u.(沒有固定 (天賦) 獎勵)' where entry=484;
update trinity_string set content_default='角色 %s 必須擁有技能 % u(%s) 在使用這個命令之前。' where entry=485;
update trinity_string set content_default='錯誤的技能遺傳素質 (%u)' where entry=486;
update trinity_string set content_default='你學會了ＧＭ默認的法術和技能。' where entry=487;
update trinity_string set content_default='你已經學了這個法術。' where entry=488;
update trinity_string set content_default='目標目標 (%s) 已經學習了那些法術。' where entry=489;
update trinity_string set content_default='%s 不懂那些法術。' where entry=490;
update trinity_string set content_default='您已經忘記了那個法術。' where entry=491;
update trinity_string set content_default='所有的法術冷卻清除為 %s。' where entry=492;
update trinity_string set content_default='法術 %u 冷卻清除為 %s。' where entry=493;
update trinity_string set content_default='命令: Additem, itemId=%i, 數量 =%i' where entry=494;
update trinity_string set content_default='命令: Additemset, itemsetId=%i' where entry=495;
update trinity_string set content_default='移除物品ID =%i, 數量 =%i 從 %s' where entry=496;
update trinity_string set content_default='不能創建物品 "% i"(數量數量: %i)' where entry=497;
update trinity_string set content_default='系統提示：你需要提供一個公會名字!' where entry=498;
update trinity_string set content_default='系統提示：玩家沒有被找到!' where entry=499;
update trinity_string set content_default='系統提示：玩家已經有一個公會!' where entry=500;
update trinity_string set content_default='公會沒被創建! (是否已經存在?)' where entry=501;
update trinity_string set content_default='沒有物品從物品庫 "% u" 裡找到。' where entry=502;
update trinity_string set content_default='The distance is: (3D) %f (2D) %f (Exact 3D) %f (Exact 2D) %f yards.' where entry=503;
update trinity_string set content_default='物品 "% i""% s" 背包 %i' where entry=504;
update trinity_string set content_default='物品 "% i" 不存在。' where entry=505;
update trinity_string set content_default='物品 "% i""% s" 已加入背包 %i' where entry=506;
update trinity_string set content_default='物品保存失敗!' where entry=507;
update trinity_string set content_default='%d- 擁有者: %s(guid: %u 帳戶: %u)%s' where entry=508;
update trinity_string set content_default='%d- 寄件人: %s(guid: %u 帳戶: %u) 接收器: %s(guid: %u 帳戶: %u)%s' where entry=509;
update trinity_string set content_default='%d- 擁有者: %s(guid: %u 帳戶: %u)%s' where entry=510;
update trinity_string set content_default='錯誤的聯編類型!' where entry=511;
update trinity_string set content_default='%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r ' where entry=512;
update trinity_string set content_default='%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' where entry=513;
update trinity_string set content_default='%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' where entry=514;
update trinity_string set content_default='%d%s - |cffffffff|H生物:%d|h[%s X:%f Y:%f Z:%f 地圖號:%d]|h|r ' where entry=515;
update trinity_string set content_default='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' where entry=516;
update trinity_string set content_default='%d (Entry: %d) - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' where entry=517;
update trinity_string set content_default='%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' where entry=518;
update trinity_string set content_default='|cffffffff|Htele:%s|h[%s]|h|r ' where entry=519;
update trinity_string set content_default='%d - |cffffffff|Hspell:%d|h[%s]|h|r ' where entry=520;
update trinity_string set content_default='%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' where entry=521;
update trinity_string set content_default='遊戲物體 (進入: %u) 不發現' where entry=522;
update trinity_string set content_default='>> 遊戲物體 %s(GUID: %u) 在 %f% f%f。 定方位 %f。' where entry=523;
update trinity_string set content_default='"""挑選的物體:

|cffffffff| Hgameobject:%d| h[%s]| h|r GUID: %u ID: %u

X: %f Y: %f Z: %f MapId: %u

定方位: %f"""' where entry=524;
update trinity_string set content_default='>> Add Game Object ''%i'' (%s) (GUID: %i) added at ''%f %f %f''.' where entry=525;
update trinity_string set content_default='%s(lowguid: %u) 運動產生器堆疊:' where entry=526;
update trinity_string set content_default='   懶惰的' where entry=527;
update trinity_string set content_default='   隨意' where entry=528;
update trinity_string set content_default='   Waypoint' where entry=529;
update trinity_string set content_default='   動物隨意' where entry=530;
update trinity_string set content_default='   困惑的' where entry=531;
update trinity_string set content_default='   對玩家對準了 %s(lowguid%u)' where entry=532;
update trinity_string set content_default='   對人對準了 %s(lowguid%u)' where entry=533;
update trinity_string set content_default='   對準到 <無效力的>' where entry=534;
update trinity_string set content_default='   家運動到 (X:%f Y:%f Z:%f)' where entry=535;
update trinity_string set content_default='   家運動對於玩家是二手的?!?' where entry=536;
update trinity_string set content_default='   出租汽車飛行' where entry=537;
update trinity_string set content_default='   未知者運動產生器 (%u)' where entry=538;
update trinity_string set content_default='Player selected NPC
DB GUID: %u, current GUID: %u.
Faction: %u.
npcFlags: %u.
Entry: %u.
DisplayID: %u (Native: %u).' where entry=539;
update trinity_string set content_default='水平: %u。' where entry=540;
update trinity_string set content_default='健康 (基礎): %u。 (最大): %u。 (湧流): %u。' where entry=541;
update trinity_string set content_default='"單位旗子: %u。電動旗子: %u。陣營型板: %u。"' where entry=542;
update trinity_string set content_default='戰利品: %u 扒手: %u 剝皮: %u' where entry=543;
update trinity_string set content_default='位置: %f% f%f。' where entry=544;
update trinity_string set content_default='*** 是一個銷售師!' where entry=545;
update trinity_string set content_default='*** 是一個訓練師!' where entry=546;
update trinity_string set content_default='副本ID: %u' where entry=547;
update trinity_string set content_default='Map: %s, Area: %s, Zone: %s, Phase: %u' where entry=714;
update trinity_string set content_default='Map: %s, Area: %s' where entry=716;
update trinity_string set content_default='命令提示：命令 .pinfo 不支持  ''rep'' 选择,玩家不在线.' where entry=550;
update trinity_string set content_default='%s 探索了所有地區。' where entry=551;
update trinity_string set content_default='%s 沒有更多的探索區。' where entry=552;
update trinity_string set content_default='%s 你探索了所有地帶。' where entry=553;
update trinity_string set content_default='%s 你掩藏了所有區域。' where entry=554;
update trinity_string set content_default='悬停启用' where entry=555;
update trinity_string set content_default='系統提示：你的等級提升 (%i)' where entry=557;
update trinity_string set content_default='系統提示：你的等級下降 (%i)' where entry=558;
update trinity_string set content_default='你的等級進度已復位。' where entry=559;
update trinity_string set content_default='該地區已被定為探索。' where entry=560;
update trinity_string set content_default='區域被設置了依照沒被探索。' where entry=561;
update trinity_string set content_default='GUID=%i ''s updateIndex: %i, value:  %i.' where entry=562;
update trinity_string set content_default='You change GUID=%i ''s UpdateIndex: %i value to %i.' where entry=563;
update trinity_string set content_default='價值索引 %u 太是大的到 %u(計數: %u)。' where entry=564;
update trinity_string set content_default='固定的 %u uint 32 價值:[操作碼]:%u[ 價值]:%u' where entry=565;
update trinity_string set content_default='你組 %u 領域:%對 uint 32 價值的 u: %u' where entry=566;
update trinity_string set content_default='固定的 %u 漂流物價值:[操作碼]:%u[ 價值]:%f' where entry=567;
update trinity_string set content_default='你組 %u 領域:%i 對漂流物價值: %f' where entry=568;
update trinity_string set content_default='拿 %u uint 32 價值:[操作碼]:%u[ 價值]:%u' where entry=569;
update trinity_string set content_default='uint 32 价值 %u 在 %u 是: %u' where entry=570;
update trinity_string set content_default='拿 %u 漂流物價值:[操作碼]:%u[ 價值]:%f' where entry=571;
update trinity_string set content_default='漂流物 %u 價值在 %u 是: %f' where entry=572;
update trinity_string set content_default='.Set32Bit:[OPCODE]:%u [VALUE]:%u' where entry=573;
update trinity_string set content_default='You set Bit of Field:%u to Value: %u' where entry=574;
update trinity_string set content_default='。Mod32 價值:[操作碼]:%u[ 價值]:%i' where entry=575;
update trinity_string set content_default='你修正了領域的價值:%u 對價值: %u' where entry=576;
update trinity_string set content_default='你現在處於隱身狀態。' where entry=577;
update trinity_string set content_default='你現在處於可見狀態。' where entry=578;
update trinity_string set content_default='挑選的玩家或人不有受害人。' where entry=579;
update trinity_string set content_default='玩家 %s 學會了所有的本種族本職業的魔法，包括任何獎勵的技能。' where entry=580;
update trinity_string set content_default='發現近的 gameobjects:(距離 %f) %u' where entry=581;
update trinity_string set content_default='刷新時間: 全部:%s 保持:%s' where entry=582;
update trinity_string set content_default='%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' where entry=583;
update trinity_string set content_default='沒有事件被找到!' where entry=584;
update trinity_string set content_default='事件不存在!' where entry=585;
update trinity_string set content_default='""" 事件 %u: %s% s 開始: %s 結束: %s 發生: %s 全程: %s 下一次狀態改變: %s"""' where entry=586;
update trinity_string set content_default='事件 %u 已經開始!' where entry=587;
update trinity_string set content_default='事件 %u 沒有開始!' where entry=588;
update trinity_string set content_default='   點運動到 (X:%f Y:%f Z:%f)' where entry=589;
update trinity_string set content_default='   恐懼運動' where entry=590;
update trinity_string set content_default='   轉移運動' where entry=591;
update trinity_string set content_default='你有有學問的整符咒在手藝: %s' where entry=592;
update trinity_string set content_default='現在禁止了帳戶:' where entry=593;
update trinity_string set content_default='|    帳戶    | BanDate    | UnbanDate| 是禁止被    | 禁令理由 |' where entry=594;
update trinity_string set content_default='現在禁止了 IPs:' where entry=595;
update trinity_string set content_default='|      IP       | BanDate    | UnbanDate| 是禁止被    | 禁令理由 |' where entry=596;
update trinity_string set content_default='在線GM:' where entry=597;
update trinity_string set content_default='|    帳戶    | GM|' where entry=598;
update trinity_string set content_default='沒有 gamemasters。' where entry=599;
update trinity_string set content_default='聯盟獲得勝利!' where entry=600;
update trinity_string set content_default='部落獲得勝利!' where entry=601;
update trinity_string set content_default='戰場戰歌峽谷爭奪分鐘倒計時中。。。' where entry=602;
update trinity_string set content_default='戰場戰歌峽谷爭奪，在 30 秒後開始。大家做好準備!' where entry=603;
update trinity_string set content_default='戰場戰歌峽谷爭奪正式開始!' where entry=604;
update trinity_string set content_default='$n 奪取了部落旗子!' where entry=605;
update trinity_string set content_default='$n 奪取了聯盟旗子!' where entry=606;
update trinity_string set content_default='部落旗子被 $n 降下!' where entry=607;
update trinity_string set content_default='聯盟旗子被 $n 降下!' where entry=608;
update trinity_string set content_default='聯盟旗子被 $n 返回了到它的基地!' where entry=609;
update trinity_string set content_default='部落旗子被 $n 返回了到它的基地!' where entry=610;
update trinity_string set content_default='部落旗子被 $n 拾起!' where entry=611;
update trinity_string set content_default='魔獸世界：聯盟旗子被 $n 拾起!' where entry=612;
update trinity_string set content_default='旗子現在被安置在他們的基地。' where entry=613;
update trinity_string set content_default='聯盟旗幟已經被重置' where entry=614;
update trinity_string set content_default='聯盟旗幟已經被重置!' where entry=615;
update trinity_string set content_default='戰場暴風之眼爭奪分鐘倒計時中....' where entry=636;
update trinity_string set content_default='戰場暴風之眼爭奪，在 30 秒後開始。大家做好準備!。' where entry=637;
update trinity_string set content_default='戰場暴風之眼爭奪正式開始!!' where entry=638;
update trinity_string set content_default='聯盟' where entry=650;
update trinity_string set content_default='部落' where entry=651;
update trinity_string set content_default='馬房' where entry=652;
update trinity_string set content_default='鐵匠' where entry=653;
update trinity_string set content_default='農場' where entry=654;
update trinity_string set content_default='木材壓搾機' where entry=655;
update trinity_string set content_default='礦' where entry=656;
update trinity_string set content_default='此 %s 採取了 % s' where entry=657;
update trinity_string set content_default='$n 保衛了 % s' where entry=658;
update trinity_string set content_default='$n 攻擊了 % s' where entry=659;
update trinity_string set content_default='$n 主持這個 % s 吧! 如果聽之任之, 這個 %s 將在分鐘之內控制它!' where entry=660;
update trinity_string set content_default='戰場阿拉西盆地爭奪分鐘倒計時中。。。' where entry=661;
update trinity_string set content_default='戰場阿拉西盆地爭奪，在 30 秒後開始。大家做好準備!' where entry=662;
update trinity_string set content_default='戰場阿拉西盆地爭奪正式開始!' where entry=663;
update trinity_string set content_default='聯盟已收集到 $1776 W 資源, 並已接近勝利!' where entry=664;
update trinity_string set content_default='部落已收集到 $1777 W 資源, 並已接近勝利!' where entry=665;
update trinity_string set content_default='你在最近的 %s 戰鬥之後，我們努力想為你頒發一個榮譽標誌卻沒有成功，結束後你會發現這個榮譽標誌的，但不是此刻,感謝你在 %s 的戰鬥。' where entry=666;
update trinity_string set content_default='聯盟有控制魔術師塔!' where entry=667;
update trinity_string set content_default='部落有控制魔術師塔!' where entry=668;
update trinity_string set content_default='聯盟有控制 Draenei 毀滅!' where entry=669;
update trinity_string set content_default='部落有控制 Draenei 毀滅!' where entry=670;
update trinity_string set content_default='聯盟有控制血小妖精塔!' where entry=671;
update trinity_string set content_default='部落有控制血小妖精塔!' where entry=672;
update trinity_string set content_default='聯盟有控制 Fel 再斷言毀滅!' where entry=673;
update trinity_string set content_default='部落有控制 Fel 再斷言毀滅!' where entry=674;
update trinity_string set content_default='聯盟有魔術師塔的失去的控制!' where entry=675;
update trinity_string set content_default='部落有魔術師塔的失去的控制!' where entry=676;
update trinity_string set content_default='聯盟有 Draenei 毀滅的失去的控制!' where entry=677;
update trinity_string set content_default='部落有 Draenei 毀滅的失去的控制!' where entry=678;
update trinity_string set content_default='聯盟有血小妖精塔的失去的控制!' where entry=679;
update trinity_string set content_default='部落有血小妖精塔的失去的控制!' where entry=680;
update trinity_string set content_default='聯盟有 Fel 的失去的控制再斷言毀滅!' where entry=681;
update trinity_string set content_default='部落有 Fel 的失去的控制再斷言毀滅!' where entry=682;
update trinity_string set content_default='%s 有帶旗子!' where entry=683;
update trinity_string set content_default='聯盟有取得了旗子!' where entry=684;
update trinity_string set content_default='部落有取得了旗子!' where entry=685;
update trinity_string set content_default='旗子已經被降下!' where entry=686;
update trinity_string set content_default='旗幟已經被重置' where entry=687;
update trinity_string set content_default='你必須達到等級 %u 才能進入競技場。' where entry=700;
update trinity_string set content_default='一分鐘後競技場爭鬥開始!' where entry=701;
update trinity_string set content_default='三十秒後競技場爭鬥開始!' where entry=702;
update trinity_string set content_default='十五秒後競技場爭鬥開始!' where entry=703;
update trinity_string set content_default='競技場爭鬥開始了!' where entry=704;
update trinity_string set content_default='你必須等待 %s 才能繼續喊話。' where entry=705;
update trinity_string set content_default='這些道具在裝備/ 存放中出現一個問題。' where entry=706;
update trinity_string set content_default='%s 免打擾狀態下無法收到悄悄話: %s' where entry=707;
update trinity_string set content_default='%s 不在機器旁: %s' where entry=708;
update trinity_string set content_default='請勿打擾' where entry=709;
update trinity_string set content_default='不在機器旁' where entry=710;
update trinity_string set content_default='"等待的隊伍狀態為 %s(Lvl: %u 到 %u) 排隊了聯盟: %u(需要至少 %u 更多) 排隊了部落: %u(需要至少 %u 更多)"' where entry=711;
update trinity_string set content_default='|cffff 0000[ BG 等待的隊伍廣播員]:|r% s-- [%u-%u] 一: %u/%u, H: %u/%u| r' where entry=712;
update trinity_string set content_default='你必須是水平 %u 對接合處競技場隊!' where entry=713;
update trinity_string set content_default='你做不會戰場水平需求' where entry=715;
update trinity_string set content_default='|cffff 0000[ BG 等待的隊伍廣播員]:|r% s-- [%u-%u] 開始!|r' where entry=717;
update trinity_string set content_default='|cffff 0000[ 競技場等待的隊伍廣播員]:|r 所有的競技場 -- 三加 : %ux% u: %u| r' where entry=718;
update trinity_string set content_default='|cffff0000[竞技场队列信息通知]:|r %s -- 已退出 : %ux%u : %u|r' where entry=719;
update trinity_string set content_default='你的團體對這一個戰場是太大的。 請對接合處重新編組。' where entry=720;
update trinity_string set content_default='你的團體對這一個競技場是太大的。 請對接合處重新編組。' where entry=721;
update trinity_string set content_default='你的團體在你的競技場隊中不有成員。 請對接合處重新編組。' where entry=722;
update trinity_string set content_default='你的團體對接合處這個比賽沒有充足玩家。' where entry=723;
update trinity_string set content_default='黃金隊贏!' where entry=724;
update trinity_string set content_default='格林隊贏!' where entry=725;
update trinity_string set content_default='没有足够的玩家。如果没有更多玩家加入以平衡人数，战场将在数分钟内结束。' where entry=726;
update trinity_string set content_default='你的團體有一個脫機成員。 以前請距離他參加。' where entry=727;
update trinity_string set content_default='你的團體有來自反對陣營的玩家。 你不能如一個團體的接合處戰場。' where entry=728;
update trinity_string set content_default='你的團體有來自不同的戰場 brakets 的玩家。 你不能如團體的接合處。' where entry=729;
update trinity_string set content_default='某人在你的宴會中已經在這一個戰場等待的隊伍中。 (S)他必須休假它在參加如團體之前。' where entry=730;
update trinity_string set content_default='某人在你的宴會中是背棄者。 你不能如團體的接合處。' where entry=731;
update trinity_string set content_default='某人在你的宴會中已經在三個戰場等待的隊伍中。 你不能夠如團體的接合處。' where entry=732;
update trinity_string set content_default='你對一個戰場或競技場地圖不能夠利用心靈傳動。' where entry=733;
update trinity_string set content_default='你對一個戰場或競技場地圖不能夠召喚玩家。' where entry=734;
update trinity_string set content_default='你在 GM 模態的必須是對在一個戰場中的一個玩家利用心靈傳動。' where entry=735;
update trinity_string set content_default='你對來自另外的一個戰場的一個戰場不能夠利用心靈傳動。 首先請休假現在的戰場。' where entry=736;
update trinity_string set content_default='競技場為除錯被設定成 1v 1 。 因此, 同樣地做不接合處團體。' where entry=737;
update trinity_string set content_default='競技場被設定成常態 playercount 。' where entry=738;
update trinity_string set content_default='戰場為除錯被設定成 1v 0 。' where entry=739;
update trinity_string set content_default='戰場被設定成常態 playercount 。' where entry=740;
update trinity_string set content_default='根据队伍等级计算竞技场点数中，也许将花上数分钟的时间。请等待……' where entry=741;
update trinity_string set content_default='正在为玩家发放竞技场点数……' where entry=742;
update trinity_string set content_default='玩家竞技场点数设置完毕。' where entry=743;
update trinity_string set content_default='Modifying played count, arena points etc. for loaded arena teams, sending updated stats to online players...' where entry=744;
update trinity_string set content_default='Modification done.' where entry=745;
update trinity_string set content_default='Done flushing Arena points.' where entry=746;
update trinity_string set content_default='不是充足玩家。 這一場遊戲意志結束在 %u 最小。' where entry=750;
update trinity_string set content_default='不是充足玩家。 這一場遊戲意志結束在 %u 秒。' where entry=751;
update trinity_string set content_default='只有部落能使用哪一入口' where entry=753;
update trinity_string set content_default='阿拉希盆地的战斗将在2分钟后开始。' where entry=754;
update trinity_string set content_default='风暴之眼的战斗将在2分钟后开始。' where entry=755;
update trinity_string set content_default='湧流挑選的名稱對於玩家 %s 重新設定如不是已知現在。' where entry=356;
update trinity_string set content_default='名稱 %u(%s) 組如湧流挑選的名稱對於玩家 %s。' where entry=355;
update trinity_string set content_default='名稱 %u(%s) 離開的從已知的名稱目錄對於玩家 %s。' where entry=354;
update trinity_string set content_default='%d (idx:%d) - [%s %s] %s %s ' where entry=350;
update trinity_string set content_default='沒有名稱發現!' where entry=351;
update trinity_string set content_default='病人名稱遺傳素質: %u' where entry=352;
update trinity_string set content_default='名稱 %u(%s) 附加的對已知的名稱目錄對於玩家 %s。' where entry=353;
update trinity_string set content_default='%d (idx:%d) - |cffffffff|Htitle:%d|h[%s %s]|h|r %s %s ' where entry=349;
update trinity_string set content_default='直到給 Alterac 山谷的戰爭 30 秒開始。 準備你們自己!' where entry=785;
update trinity_string set content_default='給 Alterac 山谷的戰爭有開始!' where entry=786;
update trinity_string set content_default='聯盟隊是流動的由於增強!' where entry=787;
update trinity_string set content_default='Invalid name' where entry=800;
update trinity_string set content_default='你做不已經充足黃金' where entry=801;
update trinity_string set content_default='你做不已經充足自由的位置' where entry=802;
update trinity_string set content_default='你的合夥人做不已經充足自由的袋子位置' where entry=803;
update trinity_string set content_default='你做不已經許可運行功能' where entry=804;
update trinity_string set content_default='未知者語言' where entry=805;
update trinity_string set content_default='你不知道那一種語言' where entry=806;
update trinity_string set content_default='請提供角色名字' where entry=807;
update trinity_string set content_default='玩家 %s 不發現或脫機' where entry=808;
update trinity_string set content_default='解釋角色 %s 不發現' where entry=809;
update trinity_string set content_default='|Hplayer:$N|h[$N]|h達成成就$a!' where entry=810;
update trinity_string set content_default='公會主人' where entry=811;
update trinity_string set content_default='官員' where entry=812;
update trinity_string set content_default='退伍軍人' where entry=813;
update trinity_string set content_default='成員' where entry=814;
update trinity_string set content_default='入會' where entry=815;
update trinity_string set content_default='警告：你进入了不允许飞行的地区，即将解除飞行坐骑！' where entry=816;
update trinity_string set content_default='離開 daemon 。。。' where entry=1000;
update trinity_string set content_default='帳戶劃除: %s' where entry=1001;
update trinity_string set content_default='帳戶 %s 不劃除了 (或許 sql 文件格式是更新)' where entry=1002;
update trinity_string set content_default='帳戶 %s 不劃除了 (未知者錯誤)' where entry=1003;
update trinity_string set content_default='帳戶產生: %s' where entry=1004;
update trinity_string set content_default='帳戶名字不可能是比 16個角色 (客戶界限) 長, 帳戶不產生了!' where entry=1005;
update trinity_string set content_default='和這個名字的帳戶已經存在!' where entry=1006;
update trinity_string set content_default='帳戶 %s 不產生了 (或許 sql 文件格式是更新)' where entry=1007;
update trinity_string set content_default='帳戶 %s 不產生了 (未知者錯誤)' where entry=1008;
update trinity_string set content_default='玩家 %s(Guid: %u) 帳戶 %s(ID: %u) 劃除。' where entry=1009;
update trinity_string set content_default='-==================================================================-' where entry=1012;
update trinity_string set content_default='|<Error>        | %20s |<Error>          |<Er>| <Error>   |' where entry=1011;
update trinity_string set content_default='-[         Account][   Character][             IP][Map][Zone][Exp][GMLev]-' where entry=1010;
update trinity_string set content_default='沒有在線玩家。' where entry=1014;
update trinity_string set content_default='帳戶 %s(ID: %u) 最多有 %u 擴充現在允許了。' where entry=1100;
update trinity_string set content_default='"那天的信息換成: %s"' where entry=1101;
update trinity_string set content_default='信息送了到 %s: %s' where entry=1102;
update trinity_string set content_default='%d - %s %s' where entry=1103;
update trinity_string set content_default='%d - %s' where entry=1104;
update trinity_string set content_default='%d - %s' where entry=1105;
update trinity_string set content_default='%d - %s %s' where entry=1106;
update trinity_string set content_default='%d - %s' where entry=1107;
update trinity_string set content_default='%d - %s %s' where entry=1108;
update trinity_string set content_default='%d - %s %s %s %s' where entry=1109;
update trinity_string set content_default='%d - %s X:%f Y:%f Z:%f MapId:%d' where entry=1110;
update trinity_string set content_default='%d - %s X:%f Y:%f Z:%f MapId:%d' where entry=1111;
update trinity_string set content_default='失敗的對開著的文件: %s' where entry=1112;
update trinity_string set content_default='帳戶 %s(%u) 有最大數量允許了角色 (客戶界限)' where entry=1113;
update trinity_string set content_default='垃圾場文件有壞掉的數據!' where entry=1114;
update trinity_string set content_default='病人角色名字!' where entry=1115;
update trinity_string set content_default='病人角色 guid!' where entry=1116;
update trinity_string set content_default='角色 guid%在使用中的 u!' where entry=1117;
update trinity_string set content_default='%d- 公會: %s(guid: %u) %s' where entry=1118;
update trinity_string set content_default='你必須使用男性或如性的女性。' where entry=1119;
update trinity_string set content_default='你變化性 %s 到 %s。' where entry=1120;
update trinity_string set content_default='你的性換成 %s 被 %s。' where entry=1121;
update trinity_string set content_default='(%u/%u+ 燙髮 %u+ 臨時僱員 %u)' where entry=1122;
update trinity_string set content_default='不是伴侶動物發現' where entry=1123;
update trinity_string set content_default='錯誤的伴侶動物類型' where entry=1124;
update trinity_string set content_default='你的伴侶動物有學問的所有人才' where entry=1125;
update trinity_string set content_default='你的伴侶動物人才有是重新設定。' where entry=1126;
update trinity_string set content_default='人才 %s 伴侶動物重新設定。' where entry=1127;
update trinity_string set content_default='%d- |cffffffff| Htaxinode:%u| h[%s% s]|h| r(地圖:%u X:%f Y:%f Z:%f)' where entry=1128;
update trinity_string set content_default='%d- %s% s(地圖:%u X:%f Y:%f Z:%f)' where entry=1129;
update trinity_string set content_default='你對視野 cinemitic 的嘗試 %u 但是它不存在。' where entry=1200;
update trinity_string set content_default='你對視野電影的嘗試 %u 但是它不存在。' where entry=1201;
update trinity_string set content_default='联盟' where entry=1300;
update trinity_string set content_default='部落' where entry=1301;
update trinity_string set content_default='%s被%s摧毁了！' where entry=1302;
update trinity_string set content_default='%s正在遭受攻击！如不采取行动，%s将摧毁它！' where entry=1303;
update trinity_string set content_default='%s被%s占领了！' where entry=1304;
update trinity_string set content_default='%s被%s占领了！' where entry=1305;
update trinity_string set content_default='%s被%s占领了！' where entry=1306;
update trinity_string set content_default='%s正在遭受攻击！如不采取行动，%s将夺取它！' where entry=1307;
update trinity_string set content_default='%s已夺取%s！矿洞中的资源将补充其战力！' where entry=1308;
update trinity_string set content_default='深铁矿洞' where entry=1309;
update trinity_string set content_default='冷齿矿洞' where entry=1310;
update trinity_string set content_default='雷矛急救站' where entry=1311;
update trinity_string set content_default='丹巴达尔南部碉堡' where entry=1312;
update trinity_string set content_default='丹巴达尔北部碉堡' where entry=1313;
update trinity_string set content_default='雷矛墓地' where entry=1314;
update trinity_string set content_default='冰翼碉堡' where entry=1315;
update trinity_string set content_default='石炉墓地' where entry=1316;
update trinity_string set content_default='石炉碉堡' where entry=1317;
update trinity_string set content_default='雪落墓地' where entry=1318;
update trinity_string set content_default='冰雪哨塔' where entry=1319;
update trinity_string set content_default='冰雪墓地' where entry=1320;
update trinity_string set content_default='哨塔高地' where entry=1321;
update trinity_string set content_default='霜狼墓地' where entry=1322;
update trinity_string set content_default='东部霜狼哨塔' where entry=1323;
update trinity_string set content_default='西部霜狼哨塔' where entry=1324;
update trinity_string set content_default='霜狼救援所' where entry=1325;
update trinity_string set content_default='奥特兰克山谷的战斗将于1分钟后开始。' where entry=1326;
update trinity_string set content_default='奥特兰克山谷的战斗将于30秒后开始。做好准备！' where entry=1327;
update trinity_string set content_default='奥特兰克山谷的战斗开始了！' where entry=1328;
update trinity_string set content_default='联盟的战力即将耗尽！' where entry=1329;
update trinity_string set content_default='部落的战力即将耗尽！' where entry=1330;
update trinity_string set content_default='霜狼的将军被杀死了！' where entry=1331;
update trinity_string set content_default='部落的将军被杀死了！' where entry=1332;
update trinity_string set content_default='奥特兰克山谷的战斗将于2分钟后开始。' where entry=1333;
update trinity_string set content_default='|cff00ff00New ticket from|r|cffff00ff %s.|r |cff00ff00Ticket entry:|r|cffff00ff %d.|r' where entry=2000;
update trinity_string set content_default='|cff00ff00Character|r|cffff00ff %s |r|cff00ff00edited his/her ticket:|r|cffff00ff %d.|r' where entry=2001;
update trinity_string set content_default='|cff00ff00Character|r|cffff00ff %s |r|cff00ff00abandoned ticket entry:|r|cffff00ff %d.|r' where entry=2002;
update trinity_string set content_default='|cff00ff00Closed by|r:|cff00ccff %s|r ' where entry=2003;
update trinity_string set content_default='|cff00ff00Deleted by|r:|cff00ccff %s|r ' where entry=2004;
update trinity_string set content_default='Ticket not found.' where entry=2005;
update trinity_string set content_default='Please close ticket before deleting it permanently.' where entry=2006;
update trinity_string set content_default='Ticket %d is already assigned.' where entry=2007;
update trinity_string set content_default='%u Tickets succesfully reloaded from the database.' where entry=2008;
update trinity_string set content_default='Showing list of open tickets.' where entry=2009;
update trinity_string set content_default='Showing list of open tickets whose creator is online.' where entry=2010;
update trinity_string set content_default='Showing list of closed tickets.' where entry=2011;
update trinity_string set content_default='Invalid name specified. Name should be that of an online Gamemaster.' where entry=2012;
update trinity_string set content_default='This ticket is already assigned to yourself. To unassign use .ticket unassign %d and then reassign.' where entry=2013;
update trinity_string set content_default='Ticket %d is not assigned, you cannot unassign it.' where entry=2014;
update trinity_string set content_default='You cannot unassign tickets from staffmembers with a higher security level than yourself.' where entry=2015;
update trinity_string set content_default='Cannot close ticket %d, it is assigned to another GM.' where entry=2016;
update trinity_string set content_default='|cff00ff00GM Comment|r: [%s]|r' where entry=2023;
update trinity_string set content_default='|cff00ff00Created by|r:|cff00ccff %s|r ' where entry=2018;
update trinity_string set content_default='|cff00ff00Last change|r:|cff00ccff %s ago|r ' where entry=2019;
update trinity_string set content_default='|cff00ff00Assigned to|r:|cff00ccff %s|r ' where entry=2020;
update trinity_string set content_default='|cff00ff00Unassigned by|r:|cff00ccff %s|r ' where entry=2021;
update trinity_string set content_default='|cff00ff00Ticket Message|r: [%s]|r' where entry=2022;
update trinity_string set content_default='|cffaaffaaTicket|r:|cffaaccff %d.|r ' where entry=2017;
update trinity_string set content_default='|cff00ff00Created|r:|cff00ccff %s ago|r ' where entry=2025;
update trinity_string set content_default='You froze player %s.' where entry=5000;
update trinity_string set content_default='It might be amusing but no... you cant freeze yourself!' where entry=5001;
update trinity_string set content_default='Invalid input check the name of target.' where entry=5002;
update trinity_string set content_default='You unfroze player %s.' where entry=5003;
update trinity_string set content_default='There are no frozen players.' where entry=5004;
update trinity_string set content_default='Following players are frozen on the server:' where entry=5005;
update trinity_string set content_default='- %s' where entry=5006;
update trinity_string set content_default='你必须在一个团队中才能进入此副本.' where entry=5007;
update trinity_string set content_default='开始在服务器播放音乐: %u ' where entry=5009;
update trinity_string set content_default='linkGUID: %u, Entry: %u (%s)' where entry=5010;
update trinity_string set content_default='You can''t teleport self to self!' where entry=5011;
update trinity_string set content_default='没有找到地图!' where entry=5012;
update trinity_string set content_default='[Continent]' where entry=5013;
update trinity_string set content_default='[Instance]' where entry=5014;
update trinity_string set content_default='[Battleground]' where entry=5015;
update trinity_string set content_default='[竞技场]' where entry=5016;
update trinity_string set content_default='[副本重置时间: %s]' where entry=5017;
update trinity_string set content_default='|cfff00000[GM Announcement]: %s|r' where entry=6613;
update trinity_string set content_default='Notification to GM''s - ' where entry=6614;
update trinity_string set content_default='|cffffff00[|c1f40af20GM Announce by|r |cffff0000%s|cffffff00]:|r %s|r' where entry=6615;
update trinity_string set content_default='Silence is ON for %s' where entry=6616;
update trinity_string set content_default='WORLD: Denying connections.' where entry=7523;
update trinity_string set content_default='WORLD: Accepting connections.' where entry=7524;
update trinity_string set content_default='部落占领了瞭望台！' where entry=10001;
update trinity_string set content_default='联盟占领了瞭望台！' where entry=10002;
update trinity_string set content_default='部落占领了竞赛场！' where entry=10003;
update trinity_string set content_default='联盟占领的竞赛场！' where entry=10004;
update trinity_string set content_default='部落占领了碎石岭！' where entry=10005;
update trinity_string set content_default='联盟占领的碎石岭！' where entry=10006;
update trinity_string set content_default='部落失去了瞭望台的控制权！' where entry=10007;
update trinity_string set content_default='联盟失去了瞭望台的控制权！' where entry=10008;
update trinity_string set content_default='部落失去了竞赛场的控制权！' where entry=10009;
update trinity_string set content_default='联盟失去了竞赛场的控制权！' where entry=10010;
update trinity_string set content_default='部落失去了碎石岭的控制权！' where entry=10011;
update trinity_string set content_default='联盟失去了碎石岭的控制权！' where entry=10012;
update trinity_string set content_default='部落占领了西部灯塔！' where entry=10013;
update trinity_string set content_default='联盟占领了西部灯塔！' where entry=10014;
update trinity_string set content_default='部落占领了东部灯塔！' where entry=10015;
update trinity_string set content_default='联盟占领了西部灯塔！' where entry=10016;
update trinity_string set content_default='部落占领了双塔墓地！' where entry=10017;
update trinity_string set content_default='联盟占领了双塔墓地！' where entry=10018;
update trinity_string set content_default='部落失去了西部灯塔的控制权！' where entry=10019;
update trinity_string set content_default='联盟失去了西部灯塔的控制权！' where entry=10020;
update trinity_string set content_default='部落失去了东部灯塔的控制权！' where entry=10021;
update trinity_string set content_default='联盟失去了东部灯塔的控制权！' where entry=10022;
update trinity_string set content_default='部落失去了双塔墓地的控制权！' where entry=10023;
update trinity_string set content_default='联盟失去了双塔墓地的控制权！' where entry=10024;
update trinity_string set content_default='部落已夺得哈兰的控制权！' where entry=10025;
update trinity_string set content_default='联盟已夺得哈兰的控制权！' where entry=10026;
update trinity_string set content_default='部落失去了哈兰的控制权！' where entry=10027;
update trinity_string set content_default='联盟失去了哈兰的控制权！' where entry=10028;
update trinity_string set content_default='部落占领了一座灵魂塔！' where entry=10029;
update trinity_string set content_default='联盟占领了一座灵魂塔！' where entry=10030;
update trinity_string set content_default='部落失去了一座灵魂塔！' where entry=10031;
update trinity_string set content_default='联盟失去了一座灵魂塔！' where entry=10032;
update trinity_string set content_default='部落占领了北地哨塔！' where entry=10033;
update trinity_string set content_default='联盟占领了北地哨塔！' where entry=10034;
update trinity_string set content_default='部落占领了东墙哨塔！' where entry=10035;
update trinity_string set content_default='联盟占领了东墙哨塔！' where entry=10036;
update trinity_string set content_default='部落占领了皇冠哨塔！' where entry=10037;
update trinity_string set content_default='联盟占领了皇冠哨塔！' where entry=10038;
update trinity_string set content_default='部落占领了病木林哨塔！' where entry=10039;
update trinity_string set content_default='联盟占领了病木林哨塔！' where entry=10040;
update trinity_string set content_default='部落失去了北地哨塔的控制权！' where entry=10041;
update trinity_string set content_default='联盟失去了北地哨塔的控制权！' where entry=10042;
update trinity_string set content_default='部落失去了东墙哨塔的控制权！' where entry=10043;
update trinity_string set content_default='联盟失去了东墙哨塔的控制权！' where entry=10044;
update trinity_string set content_default='部落失去了皇冠哨塔的控制权！' where entry=10045;
update trinity_string set content_default='联盟失去了皇冠哨塔的控制权！' where entry=10046;
update trinity_string set content_default='部落失去了病木林哨塔的控制权！' where entry=10047;
update trinity_string set content_default='联盟失去了病木林哨塔的控制权！' where entry=10048;
update trinity_string set content_default='The Horde has collected 200 silithyst!' where entry=10049;
update trinity_string set content_default='The Alliance has collected 200 silithyst!' where entry=10050;
update trinity_string set content_default='带我去北地哨塔。' where entry=10051;
update trinity_string set content_default='带我去东墙哨塔。' where entry=10052;
update trinity_string set content_default='带我去皇冠哨塔。' where entry=10053;
update trinity_string set content_default='将旗帜给我，我将为了联盟的荣耀将它带至中心灯塔！' where entry=10054;
update trinity_string set content_default='将旗帜给我，我将为了部落的荣耀将它带至中心灯塔！' where entry=10055;
update trinity_string set content_default='|cffffff00[|c00077766自动发布信息|cffffff00]: |cFFF222FF%s|r' where entry=11000;
update trinity_string set content_default='You have not chosen -1 or the current realmID that you are on.' where entry=11001;
update trinity_string set content_default='Phasemask: %u' where entry=5020;
update trinity_string set content_default='Armor: %u' where entry=5021;
update trinity_string set content_default='泰坦大门已经被联盟占领!' where entry=10063;
update trinity_string set content_default='泰坦大门已经被部落占领!' where entry=10064;
update trinity_string set content_default='%s 已经被破坏了!' where entry=10061;
update trinity_string set content_default='第一回合-  完成!' where entry=10062;
update trinity_string set content_default='远古海滩战斗打开!勇士们.为了我们的荣耀，冲！' where entry=10059;
update trinity_string set content_default='%s 受到攻击!' where entry=10060;
update trinity_string set content_default='远古海滩战场将在30秒内打开!请各位玩家准备好.' where entry=10058;
update trinity_string set content_default='远古海滩战场将在2分钟内打开!' where entry=10056;
update trinity_string set content_default='远古海滩战场将在1分钟内打开!' where entry=10057;
update trinity_string set content_default='给与第一个加入频道的玩家频道管理权"%s": 启用' where entry=5022;
update trinity_string set content_default='这个是关闭着的.' where entry=5008;
update trinity_string set content_default='编码: %u' where entry=5024;
update trinity_string set content_default='类型: %u' where entry=5025;
update trinity_string set content_default='外观编码: %u' where entry=5026;
update trinity_string set content_default='名称: %s' where entry=5027;
update trinity_string set content_default='You cannot say, yell or emote until you become level %d.' where entry=6604;
update trinity_string set content_default='You cannot whisper until you become level %d.' where entry=6605;
update trinity_string set content_default='You cannot write to channels until you become level %d.' where entry=6606;
update trinity_string set content_default='You cannot use auction until you become level %d.' where entry=6607;
update trinity_string set content_default='You cannot write tickets until you become level %d.' where entry=6608;
update trinity_string set content_default='You cannot trade until you become level %d.' where entry=6609;
update trinity_string set content_default='You cannot trade with characters lower than level %d.' where entry=6610;
update trinity_string set content_default='You cannot send mail until you become level %d.' where entry=6611;
update trinity_string set content_default='You cannot send mail to characters lower than level %d.' where entry=6612;
update trinity_string set content_default='|cff00ccff%s|r |cff00ff00Added comment|r: [%s]|r' where entry=2024;
update trinity_string set content_default='-[%16s][%12s][%15s][%3d][%4d][%d][%d]-' where entry=1013;
update trinity_string set content_default='二手的不完全鍵入擺脫指令, 需要類型它完全 (擺脫), 或指令二手的不在 RA 指令線。' where entry=1015;
update trinity_string set content_default='战场已被禁用，无法加入队列。' where entry=747;
update trinity_string set content_default='竞技场已被禁用，无法加入队列。' where entry=748;
update trinity_string set content_default='物品 ''%i'' 已经在商人的列表里存在了.' where entry=210;
update trinity_string set content_default='Entry %u not found in creature_template table.' where entry=817;
update trinity_string set content_default='Entry %u not found in sCreatureStorage. Possible new line in creature_template, but you can not add new creatures without restarting. Only modifing is allowed.' where entry=818;
update trinity_string set content_default='第二回合将在1分钟后开始。' where entry=10065;
update trinity_string set content_default='第二回合将在30秒后开始，做好准备！' where entry=10066;
update trinity_string set content_default='大门已被攻破！泰坦圣物危急！' where entry=10067;
update trinity_string set content_default='联盟占领了南部墓地！' where entry=10068;
update trinity_string set content_default='联盟占领了西部墓地！' where entry=10069;
update trinity_string set content_default='联盟占领了东部墓地！' where entry=10070;
update trinity_string set content_default='部落占领了南部墓地！' where entry=10071;
update trinity_string set content_default='部落占领了西部墓地！' where entry=10072;
update trinity_string set content_default='部落占领了东部墓地！' where entry=10073;
update trinity_string set content_default='密碼: ' where entry=62;
update trinity_string set content_default='| GUID       | Name                 | Account                      | Delete Date         |' where entry=1016;
update trinity_string set content_default='| %10u | %20s | %15s (%10u) | %19s |' where entry=1017;
update trinity_string set content_default='==========================================================================================' where entry=1018;
update trinity_string set content_default='沒找到角色.' where entry=1019;
update trinity_string set content_default='Restoring the following characters:' where entry=1020;
update trinity_string set content_default='Deleting the following characters:' where entry=1021;
update trinity_string set content_default='ERROR: You can only assign a new name if you have only selected a single character!' where entry=1022;
update trinity_string set content_default='Character ''%s'' (GUID: %u Account %u) can''t be restored: account not exist!' where entry=1023;
update trinity_string set content_default='Character ''%s'' (GUID: %u Account %u) can''t be restored: account character list full!' where entry=1024;
update trinity_string set content_default='Character ''%s'' (GUID: %u Account %u) can''t be restored: new name already used!' where entry=1025;
update trinity_string set content_default='GUID: %u Name: %s Account: %s (%u) Date: %s' where entry=1026;
update trinity_string set content_default='Lootid: %u' where entry=5028;
update trinity_string set content_default='事件開始 %u"% s"' where entry=1130;
update trinity_string set content_default='Result limit reached (max results: %d)' where entry=5029;
update trinity_string set content_default='事件停止 %u"% s"' where entry=1131;
update trinity_string set content_default='  跟隨玩家 %s (lowguid %u)' where entry=1132;
update trinity_string set content_default='   跟隨生物 %s (lowguid %u)' where entry=1133;
update trinity_string set content_default='Areatrigger debugging turned on.' where entry=1202;
update trinity_string set content_default='Areatrigger debugging turned off.' where entry=1203;
update trinity_string set content_default='You have reached areatrigger %u.' where entry=1204;
update trinity_string set content_default='城市' where entry=819;
update trinity_string set content_default='%s calls for help!' where entry=5035;
update trinity_string set content_default='   跟隨 <NULL>' where entry=1134;
update trinity_string set content_default='列出已已學天賦:' where entry=1135;
update trinity_string set content_default='SQL driver query logging enabled.' where entry=1027;
update trinity_string set content_default='SQL driver query logging disabled.' where entry=1028;
update trinity_string set content_default='给与第一个加入频道的玩家频道管理权"%s": 禁用' where entry=5023;
update trinity_string set content_default='|cff00ff00Ticket Response|r: [%s]|r' where entry=2029;
update trinity_string set content_default='本次战斗将在2分钟内开始.' where entry=1205;
update trinity_string set content_default='本次战斗将在1分钟内开始.' where entry=1206;
update trinity_string set content_default='战斗开始了！' where entry=1208;
update trinity_string set content_default='本次战斗将在30秒内开始!' where entry=1207;
update trinity_string set content_default='已被联盟占领' where entry=1209;
update trinity_string set content_default='已被部落占领' where entry=1210;
update trinity_string set content_default='%s 赢得了胜利!' where entry=1211;
update trinity_string set content_default='西大门 %s 被破坏!' where entry=1212;
update trinity_string set content_default='东侧%s已被摧毁！' where entry=1213;
update trinity_string set content_default='南侧%s已被摧毁！' where entry=1214;
update trinity_string set content_default='北侧%s已被摧毁！' where entry=1215;
update trinity_string set content_default='$n突袭了%s！' where entry=1216;
update trinity_string set content_default='$n守住了%s！' where entry=1217;
update trinity_string set content_default='$n突袭了%s！如不采取行动，%s将在1分钟内控制它！' where entry=1218;
update trinity_string set content_default='%s占领了%s！' where entry=1219;
update trinity_string set content_default='车间' where entry=1220;
update trinity_string set content_default='码头' where entry=1221;
update trinity_string set content_default='精炼厂' where entry=1222;
update trinity_string set content_default='矿厂' where entry=1223;
update trinity_string set content_default='机场' where entry=1224;
update trinity_string set content_default='Found near creatures (distance %f): %u ' where entry=556;
update trinity_string set content_default='你已禁言%s，时长%u分钟，下次登录生效。原因: %s.' where entry=283;
update trinity_string set content_default='你的閒談將被關閉 %u 分鐘。' where entry=300;
update trinity_string set content_default='玩家%s %s (guid: %u) 帐号: %s (id: %u) G M等级: %u 最后IP: %s 最后登陆: %s Latency: %ums' where entry=548;
update trinity_string set content_default='   (找到天賦: %u 已使用天賦點: %u)' where entry=1136;
update trinity_string set content_default='%s充滿恐懼地想要轉身逃跑！' where entry=5030;
update trinity_string set content_default='Dev mode is ON' where entry=1137;
update trinity_string set content_default='Dev mode is OFF' where entry=1138;
update trinity_string set content_default='There are pending open tickets, please close them first!' where entry=2027;
update trinity_string set content_default='All closed tickets were deleted and counter is reseted to |cffff00ff 1|r' where entry=2028;
update trinity_string set content_default='AI名称: %s 脚本名称: %s' where entry=5031;
update trinity_string set content_default='   Follow player %s (lowguid %u)' where entry=1139;
update trinity_string set content_default='   Follow creature %s (lowguid %u)' where entry=1140;
update trinity_string set content_default='   Follow <NULL>' where entry=1141;
update trinity_string set content_default='   Effect movement' where entry=1142;
update trinity_string set content_default='Target''s moveFlags: %u, moveFlagsExtra: %u.' where entry=1143;
update trinity_string set content_default='Target''s moveFlags set to: %u, moveFlagsExtra to: %u' where entry=1144;
update trinity_string set content_default='No battleground found!' where entry=5032;
update trinity_string set content_default='No achievement criteria found!' where entry=5033;
update trinity_string set content_default='No outdoor PvP found!' where entry=5034;
update trinity_string set content_default='%s has been captured by %s ' where entry=12050;
update trinity_string set content_default='%s is under attack by %s' where entry=12051;
update trinity_string set content_default='The Broken Temple siege workshop' where entry=12052;
update trinity_string set content_default='Eastspark siege workshop' where entry=12053;
update trinity_string set content_default='Westspark siege workshop' where entry=12054;
update trinity_string set content_default='The Sunken Ring siege workshop' where entry=12055;
update trinity_string set content_default='Alliance' where entry=12057;
update trinity_string set content_default='Horde' where entry=12056;
update trinity_string set content_default='The battle for Wintergrasp is about to begin!' where entry=12058;
update trinity_string set content_default='You have reached Rank 1: Corporal' where entry=12059;
update trinity_string set content_default='You have reached Rank 2: First Lieutenant' where entry=12060;
update trinity_string set content_default='The south-eastern keep tower' where entry=12061;
update trinity_string set content_default='The north-eastern keep tower' where entry=12062;
update trinity_string set content_default='The south-western keep tower' where entry=12063;
update trinity_string set content_default='The north-western keep tower' where entry=12064;
update trinity_string set content_default='%s has been damaged !' where entry=12065;
update trinity_string set content_default='%s has been destroyed!' where entry=12066;
update trinity_string set content_default='The battle for Wintergrasp begin!' where entry=12067;
update trinity_string set content_default='%s has successfully defended the Wintergrasp fortress!' where entry=12068;
update trinity_string set content_default='The southern tower' where entry=12069;
update trinity_string set content_default='The eastern tower' where entry=12070;
update trinity_string set content_default='The western tower' where entry=12071;
update trinity_string set content_default='The Wintergrasp fortress has been captured by %s !' where entry=12072;
update trinity_string set content_default='Cheat Command Status:' where entry=357;
update trinity_string set content_default='Godmode: %s.' where entry=358;
update trinity_string set content_default='Casttime: %s.' where entry=359;
update trinity_string set content_default='Cooldown: %s.' where entry=360;
update trinity_string set content_default='Power: %s.' where entry=361;
update trinity_string set content_default='Waterwalk: %s.' where entry=362;
update trinity_string set content_default='Player name: %s, State: %s, Dungeons: %u (%s), Roles: %s, Comment: %s' where entry=9980;
update trinity_string set content_default='LfgGroup?: %u, State: %s, Dungeon: %u' where entry=9981;
update trinity_string set content_default='Not in group' where entry=9982;
update trinity_string set content_default='Queues cleared' where entry=9983;
update trinity_string set content_default='Lfg options: %u' where entry=9984;
update trinity_string set content_default='Lfg options changed' where entry=9985;
update trinity_string set content_default='None' where entry=9986;
update trinity_string set content_default='Role check' where entry=9987;
update trinity_string set content_default='Queued' where entry=9988;
update trinity_string set content_default='Proposal' where entry=9989;
update trinity_string set content_default='Vote kick' where entry=9990;
update trinity_string set content_default='In dungeon' where entry=9991;
update trinity_string set content_default='Finished dungeon' where entry=9992;
update trinity_string set content_default='Raid browser' where entry=9993;
update trinity_string set content_default='Tank' where entry=9994;
update trinity_string set content_default='Healer' where entry=9995;
update trinity_string set content_default='Dps' where entry=9996;
update trinity_string set content_default='Leader' where entry=9997;
update trinity_string set content_default='None' where entry=9998;
update trinity_string set content_default='Error' where entry=9999;
update trinity_string set content_default='* has gossip (%u)' where entry=820;
update trinity_string set content_default='* is quest giver (%u)' where entry=821;
update trinity_string set content_default='* is class trainer (%u)' where entry=822;
update trinity_string set content_default='* is profession trainer(%u)' where entry=823;
update trinity_string set content_default='* is ammo vendor (%u)' where entry=824;
update trinity_string set content_default='* is food vendor(%u)' where entry=825;
update trinity_string set content_default='* is poison vendor (%u)' where entry=826;
update trinity_string set content_default='* is reagent vendor (%u)' where entry=827;
update trinity_string set content_default='* can repair (%u)' where entry=828;
update trinity_string set content_default='* is flight master (%u)' where entry=829;
update trinity_string set content_default='* is spirit healer (%u)' where entry=830;
update trinity_string set content_default='* is spirit guide (%u)' where entry=831;
update trinity_string set content_default='* is innkeeper (%u)' where entry=832;
update trinity_string set content_default='* is banker (%u)' where entry=833;
update trinity_string set content_default='* is petitioner (%u)' where entry=834;
update trinity_string set content_default='* is tabard designer (%u)' where entry=835;
update trinity_string set content_default='* is battle master (%u)' where entry=836;
update trinity_string set content_default='* is auctioneer (%u)' where entry=837;
update trinity_string set content_default='* is stable master (%u)' where entry=838;
update trinity_string set content_default='* is guild banker (%u)' where entry=839;
update trinity_string set content_default='* has spell click (%u)' where entry=840;
update trinity_string set content_default='* is mailbox (%u)' where entry=841;
update trinity_string set content_default='* is player vehicle (%u)' where entry=842;
update trinity_string set content_default='%s is already in a group!' where entry=1145;
update trinity_string set content_default='%s joined %s''s group.' where entry=1146;
update trinity_string set content_default='%s is not in a group!' where entry=1147;
update trinity_string set content_default='Group is full!' where entry=1148;
update trinity_string set content_default='Group type: %s' where entry=1149;
update trinity_string set content_default='Name: %s (%s), GUID: %u, Flags: %s, Roles: %s' where entry=1150;
update trinity_string set content_default='Ban time remaining: %s, Banned by: %s, Reason: %s' where entry=453;
update trinity_string set content_default='Wrong parameter id: %u, does not exist' where entry=63;
update trinity_string set content_default='Wrong parameter realmId: %d' where entry=64;
update trinity_string set content_default='Couldn''t add group %u (%s) realmId %d. Account %u (%s) already has that group' where entry=65;
update trinity_string set content_default='Couldn''t remove group %u (%s) realmId %d. Account %u (%s) does not have that group' where entry=66;
update trinity_string set content_default='Added group %u (%s) realmId %d to account %u (%s)' where entry=67;
update trinity_string set content_default='Removed group %u (%s) realmId %d from account %u (%s)' where entry=68;
update trinity_string set content_default='Account %u (%s) groups:' where entry=69;
update trinity_string set content_default='Empty List' where entry=70;
update trinity_string set content_default='- %u (%s)' where entry=71;
update trinity_string set content_default='Couldn''t grant role %u (%s) realmId %d. Account %u (%s) already has that role' where entry=72;
update trinity_string set content_default='Couldn''t grant role %u (%s) realmId %d. Account %u (%s) has that role in deny list' where entry=73;
update trinity_string set content_default='Granted role %u (%s) realmId %d to account %u (%s)' where entry=74;
update trinity_string set content_default='Couldn''t deny role %u (%s) realmId %d. Account %u (%s) already has that role' where entry=75;
update trinity_string set content_default='Couldn''t deny role %u (%s) realmId %d. Account %u (%s) has that role in deny list' where entry=76;
update trinity_string set content_default='Denied role %u (%s) realmId %d to account %u (%s)' where entry=77;
update trinity_string set content_default='Denied role %u (%s) realmId %d to account %u (%s)' where entry=78;
update trinity_string set content_default='Couldn''t revoke role %u (%s) realmId %d. Account %u (%s) does not have that role' where entry=79;
update trinity_string set content_default='Account %u (%s) granted roles:' where entry=80;
update trinity_string set content_default='Account %u (%s) denied roles:' where entry=81;
update trinity_string set content_default='Couldn''t grant permission %u (%s) realmId %d. Account %u (%s) already has that permission' where entry=82;
update trinity_string set content_default='Couldn''t grant permission %u (%s) realmId %d. Account %u (%s) has that permission in deny list' where entry=83;
update trinity_string set content_default='Granted permission %u (%s) realmId %d to account %u (%s)' where entry=84;
update trinity_string set content_default='Couldn''t deny permission %u (%s) realmId %d. Account %u (%s) already has that permission' where entry=85;
update trinity_string set content_default='Couldn''t deny permission %u (%s) realmId %d. Account %u (%s) has that permission in deny list' where entry=86;
update trinity_string set content_default='Denied permission %u (%s) realmId %d to account %u (%s)' where entry=87;
update trinity_string set content_default='Revoked permission %u (%s) realmId %d to account %u (%s)' where entry=88;
update trinity_string set content_default='Couldn''t revoke permission %u (%s) realmId %d. Account %u (%s) does not have that permission' where entry=89;
update trinity_string set content_default='Account %u (%s) granted permissions:' where entry=90;
update trinity_string set content_default='Account %u (%s) denied permissions:' where entry=91;
update trinity_string set content_default='Account %u (%s) global permissions:' where entry=92;
update trinity_string set content_default='Groups:' where entry=93;
update trinity_string set content_default='Roles:' where entry=94;
update trinity_string set content_default='Permissions:' where entry=95;
update trinity_string set content_default='已登录时间: %s 等级: %u 金钱: %ug%us%uc' where entry=549;
update trinity_string set content_default='EquipmentId: %u (Original: %u).' where entry=5036;
update trinity_string set content_default='Player %s cannot whisper you any longer.' where entry=363;
update trinity_string set content_default='Mail List Info: # of mails: %u, Player: %s(%u)' where entry=1151;
update trinity_string set content_default='Mail Id: %u Title: "%s" Money: %ug%us%uc' where entry=1152;
update trinity_string set content_default='Sender: %s(%u), Receiver: %s(%u)' where entry=1153;
update trinity_string set content_default='Time deliver: %s, Time expire: %s' where entry=1154;
update trinity_string set content_default='Item: %s[Entry:%u Guid:%u Count:%u]' where entry=1155;
update trinity_string set content_default='Mail List Info: No mail found for this character.' where entry=1156;
update trinity_string set content_default='Guide me to the Sunken Ring Graveyard.' where entry=20071;
update trinity_string set content_default='Guide me to the Broken Temple Graveyard.' where entry=20072;
update trinity_string set content_default='Guide me to the Eastspark Graveyard.' where entry=20074;
update trinity_string set content_default='Guide me to the Westspark Graveyard.' where entry=20073;
update trinity_string set content_default='Guide me to the Fortress Graveyard.' where entry=20070;
update trinity_string set content_default='Guide me back to the Horde landing camp.' where entry=20075;
update trinity_string set content_default='Guide me back to the Alliance landing camp.' where entry=20076;
update trinity_string set content_default='Queue for Wintergrasp.' where entry=20077;
update trinity_string set content_default='The guild name ''%s'' is already taken' where entry=96;
update trinity_string set content_default='Changed guild name ''%s'' to ''%s''' where entry=97;
update trinity_string set content_default='''%s'' already exists as character name, choose another one' where entry=98;
update trinity_string set content_default='Player ''%s'' forced rename to ''%s''' where entry=99;
update trinity_string set content_default='This name is reserved, choose another one' where entry=167;
update trinity_string set content_default='Invalid gameobject type, must be a destructible building.' where entry=176;
update trinity_string set content_default='Gameobject %s (GUID: %u) damaged %u (actual health: %u).' where entry=177;
update trinity_string set content_default='Guild: %s (%u) Rank: %s Note: %s OffNote: %s' where entry=749;
update trinity_string set content_default='â”‚ Last IP: %s (Locked: %s)' where entry=752;
update trinity_string set content_default='â”‚ Level: %u (%u/%u XP (%u XP left))' where entry=843;
update trinity_string set content_default='â”‚ Race: %s %s, %s' where entry=844;
update trinity_string set content_default='â”‚ Alive ?: %s' where entry=845;
update trinity_string set content_default='â”‚ Phase: %u' where entry=846;
update trinity_string set content_default='â”‚ Money: %ug%us%uc' where entry=847;
update trinity_string set content_default='â”‚ Map: %s, Area: %s, Zone: %s' where entry=848;
update trinity_string set content_default='â”‚ Guild: %s (ID: %u)' where entry=849;
update trinity_string set content_default='â”œâ”€ Rank: %s' where entry=850;
update trinity_string set content_default='â”œâ”€ Note: %s' where entry=851;
update trinity_string set content_default='â”œâ”€ O. Note: %s' where entry=852;
update trinity_string set content_default='â”‚ Played time: %s' where entry=853;
update trinity_string set content_default='â”” Mails: %d Read/%u Total' where entry=854;
update trinity_string set content_default='Male' where entry=855;
update trinity_string set content_default='Female' where entry=856;
update trinity_string set content_default='Arena team [%u] not found' where entry=857;
update trinity_string set content_default='There is already an arena team named "%s"' where entry=858;
update trinity_string set content_default='%s is already in an arena team of that size' where entry=859;
update trinity_string set content_default='Arena Team In Combat' where entry=860;
update trinity_string set content_default='Arena with name: "%s" or silmilar not found' where entry=861;
update trinity_string set content_default='[%s] not member of the team "%s"' where entry=862;
update trinity_string set content_default='[%s] already capitan in the team "%s"' where entry=863;
update trinity_string set content_default='New ArenaTeam created [Name: "%s"][Id: %u][Type: %u][Captain GUID: %u]' where entry=864;
update trinity_string set content_default='Arena team Name: "%s"[Id: %u] disbanded' where entry=865;
update trinity_string set content_default='Arena team [Id: %u] change from "%s" to "%s"' where entry=866;
update trinity_string set content_default='Arena team Name: "%s"[Id: %u] change capitan from[%s] to [%s]' where entry=867;
update trinity_string set content_default='Arena team: "%s"[%u] - Rating: %u - Type: %ux%u' where entry=868;
update trinity_string set content_default='Name:"%s"[guid:%u] - PR: %u - %s' where entry=869;
update trinity_string set content_default='|"%s"[ID:%u](%ux%u)|' where entry=870;
update trinity_string set content_default='â”‚ Level: %u' where entry=871;
